Repository Monkestation/Vanderlin, pull requests merged in 2025-03, with the labels that each got.

#889 Patches up food.dmi.
  icons/roguetown/items/food.dmi
Labels: Sprites

#869 Adds dungeon entrance to Malums Anvil
  _maps/map_files/vanderlin/otherz/vanderlin_mountain.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#940 Documents and adds defines for Elasticsearch data
  code/__DEFINES/elastic.dm
  code/controllers/subsystem/death_arena.dm
  code/controllers/subsystem/elastic.dm
  code/controllers/subsystem/storyteller.dm
  code/datums/ai/behaviours/eat_food/eat_body.dm
  code/datums/components/crafting/crafting.dm
  code/game/machinery/trams_and_elevators/lift_master.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/closed/wall/walls.dm
  code/modules/error_handler/error_handler.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  code/modules/underworld/underworld.dm
  stonekeep.dme
Labels: documentation, code maintenance, logging

#866 Adds Far Travel Subsystem and Maps in a temporary location.
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/structures/train.dm
  icons/roguetown/items/train.dmi
  stonekeep.dme
Labels: feature, administration, Mapping

#813 Hole of Submission is now stockpile with no payout.
  code/game/objects/structures/fake_machines/submission.dm
Labels: feature

#804 Court Agents Spawn in the Keep Guest Meeting Room
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/adventurer/court_hand.dm
Labels: Mapping

#951 admin logging for parry and dodging
  code/game/atoms.dm
  code/modules/mob/living/roguetownprocs.dm
Labels: logging

#953 bog gate doors are unlocked using the forest garrison keys
  _maps/map_files/vanderlin/otherz/vanderlin_bog.dmm
Labels: Mapping

#892 Updates the Vampire Lord Mansion
  _maps/map_files/generic/CentCom.dmm
Labels: active test merge, Mapping

#943 Dipping knives into poison now takes 10 units but only injects 0.5u per slash (Also lets profane dagger dip in non bottle containers)
  code/datums/elements/tipped_item.dm
Labels: active test merge

#915 Remove unused skills, change medicine description and give it a dream
  code/datums/skills/craft.dm
  code/datums/skills/labor.dm
  code/datums/skills/misc.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/merchant.dm
  code/modules/jobs/job_types/nobility/merchant.dm
Labels: removal

#973 makes a lich spawn landmark
  _maps/map_files/vanderlin/otherz/vanderlin_forest.dmm
  code/_globalvars/lists/mapping.dm
  code/game/objects/effects/landmarks.dm
  code/modules/antagonists/villain/lich.dm
Labels: Mapping

#900 More crafting options for beds, and bed sheet fix
  _maps/custom/roguehamlet.dmm
  _maps/custom/roguehamlet1.dmm
  _maps/custom/roguetown.dmm
  _maps/custom/stonekeep.dmm
  _maps/map_files/matthios_tomb/room/AcidMageTower.dmm
  _maps/map_files/matthios_tomb/room/Goonies.dmm
  _maps/map_files/matthios_tomb/room/hctomb1.dmm
  _maps/map_files/old_maps/roguetown2.dmm
  _maps/map_files/old_maps/roguetown4.dmm
  _maps/map_files/old_maps/roguetown5.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/rogueworld/roguetown.dmm
  _maps/map_files/templates/malums_anvil_dungeons/mountaintown.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/game/objects/items/bedsheets.dm
  code/game/objects/structures/beds_chairs/bed.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/crafting/slapcrafting/recipes/carpentry/structures.dm
  code/modules/crafting/slapcrafting/steps/give_item.dm
  icons/roguetown/misc/structure.dmi
Labels: active test merge, Mapping

#881 Pear Pie's and Grenzelhoft bread spread
  code/datums/pollutants/foods.dm
  code/game/objects/effects/decals/cleanable/food.dm
  code/modules/cooking/NeuFood.dm
  code/modules/cooking/cooked/NeuFood_pies.dm
  code/modules/cooking/raw/NeuFood_dough.dm
  code/modules/cooking/raw/NeuFood_meat.dm
  code/modules/crafting/slapcrafting/orderless/pies.dm
  icons/roguetown/items/food.dmi
Labels: active test merge

#933 Beauty update
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/heritage.dm
  code/datums/stress/negative_events.dm
  code/datums/stress/neutral_events.dm
  code/datums/stress/positive_events.dm
  code/modules/jobs/job_types/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/apprentices/prince.dm
  code/modules/jobs/job_types/church/monk.dm
  code/modules/jobs/job_types/church/templar.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/stats.dm
  stonekeep.dme
Labels: active test merge

#917 Soapification
  code/__DEFINES/cleaning.dm
  code/__HELPERS/unsorted.dm
  code/datums/components/_component.dm
  code/datums/components/cleaning.dm
  code/datums/components/slippery.dm
  code/datums/stress/positive_events.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/soap.dm
  code/modules/crafting/quality_of_crafting/cooking.dm
  code/modules/jobs/job_types/peasants/bathmaid.dm
  stonekeep.dme
Labels: active test merge

#952 Admins can now adjust triumphs and see a player's triumph value
  code/controllers/subsystem/triumph/triumph_adjust_procs.dm
  code/controllers/subsystem/triumph/triumphs_unsorted.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_triumphs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  stonekeep.dme
Labels: active test merge

#944 MatthiosAddition
  _maps/map_files/matthios_tomb/room/SteamCastle.dmm
  code/datums/dungeon_generator/dungeon_templates/rooms/common.dm
Labels: Mapping

#896 Refactors datum/browser/modal, adds TGUI "inspired" browser-based input procs
  code/__DEFINES/browser.dm
  code/__DEFINES/dcs/signals/signals_movable.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/game.dm
  code/__HELPERS/lordcolor.dm
  code/__HELPERS/roundend.dm
  code/__HELPERS/text.dm
  code/controllers/subsystem/librarian.dm
  code/controllers/subsystem/painting.dm
  code/controllers/subsystem/vote.dm
  code/datums/browser.dm
  code/datums/browser/_browser.dm
  code/datums/browser/modal/_modal.dm
  code/datums/browser/modal/alert.dm
  code/datums/browser/modal/input/input_list.dm
  code/datums/browser/modal/input/input_text.dm
  code/datums/datum.dm
  code/datums/gods/faiths/divine_pantheon.dm
  code/datums/gods/faiths/forgotten.dm
  code/datums/gods/faiths/inhumen_pantheon.dm
  code/datums/mind.dm
  code/datums/outfit.dm
  code/datums/sleep_advancement.dm
  code/game/objects/items/cup.dm
  code/game/objects/structures/fake_machines/steward.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/commandreport.dm
  code/modules/admin/verbs/schizohelp.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_descriptors.dm
  code/modules/error_handler/error_viewer.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/carbon/human/species_types/other/tiefling.dm
  code/modules/mob/mob_movement.dm
  code/modules/paperwork/paper.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  code/modules/tgui/subsystem.dm
  html/browser/common.css
  interface/interface.dm
  stonekeep.dme
Labels: feature, active test merge, code maintenance

#977 Arrows can be dipped in reagents, cloth and rope can be tied directly to belt slot
  code/datums/elements/tipped_item.dm
  code/game/objects/items/natural/clothfibersthorn.dm
  code/game/objects/items/ropechainbola.dm
  code/game/objects/items/weapons/melee/knives.dm
  code/game/objects/items/weapons/ranged/ammo.dm
  code/modules/clothing/belt/misc.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/crafting/quality_of_crafting/natural_items.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/reagents/reagent_containers/bottles/_bottle.dm
Labels: active test merge

#983 removes the malum amulet cage from the armorsmith
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping, removal

#976 Logging for equipping a weapon
  code/modules/mob/inventory.dm
Labels: active test merge, logging

#989 logs fix
  code/game/atoms.dm
Labels: active test merge, logging

#991 Veteran/Captain's room fix
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#945 audit and autodoc for mind.dm
  code/datums/mind.dm
  code/modules/paperwork/contract.dm
  stonekeep.dme
Labels: active test merge

#995 All Feeding Holes are now Hole of Submission
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#950 Foreigner
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/datums/migrants/migrant_role.dm
  code/datums/migrants/waves/crusader_wave.dm
  code/datums/migrants/waves/dwarven_company.dm
  code/datums/migrants/waves/grenzelhoft_wave.dm
  code/datums/migrants/waves/heartfell_wave.dm
  code/datums/migrants/waves/prisoner_wave.dm
  code/datums/migrants/waves/returning_bannermen.dm
  code/datums/migrants/waves/rockhill_wave.dm
  code/datums/migrants/waves/zybantine_wave.dm
  code/datums/stress/negative_events.dm
  code/datums/stress/neutral_events.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/adventurer.dm
  code/modules/jobs/job_types/adventurer/bandit.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/bard.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/grenzelhoft.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/merchant.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/preacher.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/zybantine.dm
  code/modules/jobs/job_types/church/adept.dm
  code/modules/jobs/job_types/church/inquisitor.dm
  code/modules/jobs/job_types/other/mercenary.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: active test merge

#992 reduce bloat in parry/dodge logs
  code/modules/mob/living/roguetownprocs.dm
Labels: active test merge, logging

#963 Flavor text and headshots
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/topic.dm
Labels: active test merge

#1003 Noose & Gallows Update (Fixed this time)
  code/game/objects/items/ropechainbola.dm
  code/game/objects/lighting/lantern_post.dm
  code/modules/crafting/slapcrafting/recipes/carpentry/structures.dm
  code/modules/crafting/slapcrafting/steps/give_item.dm
Labels: active test merge

#1018 Mentor help resolve for admins
  code/controllers/subsystem/plexora.dm
  code/modules/admin/chat_commands.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: active test merge

#903 Platterification
  _maps/custom/roguehamlet.dmm
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/matthios_tomb/room/TheatherOfSadism.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/templates/malums_anvil_dungeons/embercradle.dmm
  _maps/map_files/templates/malums_anvil_dungeons/mountaintown.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/roguehamlet/roguehamlet.dmm
  code/datums/pottery_recipes/pottery.dm
  code/game/objects/items/kitchen.dm
  code/game/objects/items/plate.dm
  code/modules/cargo/supply_packs/tools.dm
  code/modules/cooking/NeuFood.dm
  code/modules/crafting/anvil_recipes/tools.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/food_and_drinks/food/snacks.dm
  icons/roguetown/items/cooking.dmi
Labels: active test merge, Mapping

#939 Fixes triumph leaderboard not showing anybody
  code/controllers/subsystem/triumph/triumphs.dm
Labels: fix, active test merge, code maintenance, DO NOT MERGE

#1052 Master's rod admin logging
  code/game/objects/items/weapons/melee/special.dm
Labels: logging

#1001 Crit code cleanup
  code/modules/mob/living/living_wounds.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: active test merge

#1045 Forest Guard Armor... Again!
  code/__DEFINES/roguetown.dm
  code/modules/clothing/armor/forestguardarmor.dm
  code/modules/jobs/job_types/garrison/forestguard.dm
  code/modules/jobs/job_types/garrison/forestwarden.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/onmob/64x64/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/special/forest_guard.dmi
  icons/roguetown/clothing/special/onmob/forest_guard.dmi
  icons/roguetown/clothing/special/onmob/warden_64x64.dmi
  stonekeep.dme
Labels: active test merge

#984 Dredge Adventuring Class
  code/modules/jobs/job_types/adventurer/types/combat/dredge.dm
  stonekeep.dme
Labels: active test merge

#1063 Fixes patreon headshot bug
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: active test merge

#1049 UI improvements
  code/datums/migrants/migrant_pref.dm
  code/game/objects/structures/fake_machines/drugmachine.dm
  code/game/objects/structures/fake_machines/merchant.dm
  code/game/objects/structures/fake_machines/scomm.dm
  code/game/objects/structures/fake_machines/steward.dm
  code/game/objects/structures/fake_machines/submission.dm
  code/game/objects/structures/fake_machines/vendor.dm
Labels: active test merge

#1047 Storyteller mending
  code/__DEFINES/storytellers.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/storytellers/gods.dm
Labels: active test merge

#1077 Hilly Murderwoods + Bandit Den Fix
  _maps/map_files/vanderlin/otherz/vanderlin_forest.dmm
Labels: Mapping

#1098 Athletics fixed for bandit classes
  code/modules/jobs/job_types/adventurer/types/antag/brigand.dm
  code/modules/jobs/job_types/adventurer/types/antag/knave.dm
  code/modules/jobs/job_types/adventurer/types/antag/sellsword.dm
Labels: balance

#1085 Fix tiefling tails not loading... among other things.
  code/__HELPERS/mobs.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/species_types/other/tiefling.dm
  html/browser/common.css
Labels: fix, code maintenance, unatomized

#1061 Admemes again
  code/modules/admin/admin_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/verbs/ooc.dm
Labels: active test merge

#1105 Fixes cure rot client color bug
  code/modules/spells/spell_types/invoked/acolyte/pestra.dm
Labels: active test merge

#1111 {FIX CHAT} verb
  code/modules/client/verbs/ooc.dm
Labels: active test merge

#1095 Fixes coppiette (real)
  code/modules/cooking/raw/NeuFood_processed.dm
Labels: tweak

#1055 No more lockhash and custom key update
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/roguetown.dm
  code/game/objects/items/contraption.dm
  code/game/objects/items/keys.dm
  code/game/objects/items/locks.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/pillory.dm
  code/modules/crafting/anvil_recipes/tools.dm
  code/modules/crafting/artificer/misc.dm
Labels: active test merge, Mapping

#1123 No one knows a foreigner's job
  code/modules/mob/living/carbon/human/examine.dm
Labels: active test merge

#1110 fixes pilgrims and adventurers getting borked when becoming a vampire lord
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/role_class_handler/role_class_handler.dm
  code/datums/migrants/migrant_pref.dm
  code/modules/antagonists/villain/vampirelord.dm
  code/modules/events/antagonist/solo/vampires_and_werewolves.dm
Labels: active test merge

#1100 Actually fixes master'd rod
  code/game/objects/items/weapons/melee/special.dm
Labels: active test merge

#1107 Slapcrafting improvements
  code/game/objects/items/natural.dm
  code/modules/crafting/quality_of_crafting/_base.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/crafting/quality_of_crafting/natural_items.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
Labels: active test merge

#1156 Removes Int Buff From Steam Armor
  code/datums/status_effects/rogue/roguebuff.dm
Labels: balance

#1138 half orcs are STINKY BECAUSE I HATE THEM
  code/datums/components/rotting.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/other/halforc.dm
Labels: TEST MERGE ONLY

#1169 No more microdosing Moondust
  code/modules/reagents/reagent_containers/powder.dm
Labels: balance

#1012 Hidden Door Unmeta
  _maps/map_files/matthios_tomb/room/AcidMageTower.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/traits.dm
  code/game/area/roguetownareas.dm
  code/game/objects/structures/hidden_doors.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/redstone.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/jobs/job_types/apprentices/prince.dm
  code/modules/jobs/job_types/nobility/consort.dm
  code/modules/jobs/job_types/nobility/hand.dm
  code/modules/jobs/job_types/nobility/lord.dm
  code/modules/jobs/job_types/peasants/butler.dm
  code/modules/paperwork/rogue.dm
  icons/effects/hidden_door.dmi
  icons/turf/areas.dmi
  icons/turf/roguefloor.dmi
  sound/music/area/eora.ogg
Labels: active test merge, Mapping

#1148 Grenzelhoft accent
  code/__DEFINES/accents.dm
  strings/grenz_replacement.json
Labels: active test merge

#1201 Bunch of additional tiles for mappers. Rosewood rejoyce.
  code/game/turfs/closed/minerals.dm
  code/game/turfs/open/water.dm
  icons/turf/newwater.dmi
  icons/turf/roguefloor.dmi
  icons/turf/roguewall.dmi
  icons/turf/walls/cwall_cold.dmi
  icons/turf/walls/cwall_red.dmi
Labels: Mapping

#1182 Gives the Apothecary Master Alchemy, removes lockpicking and pickpocketing from their skills.
  code/modules/jobs/job_types/nobility/nightman.dm
Labels: removal

#1174 Dredge mage and Magos of heartfelt get mana regen
  code/datums/migrants/waves/heartfell_wave.dm
  code/modules/jobs/job_types/adventurer/types/combat/dredge.dm
Labels: balance

#1206 Let players see current map, next map, ping and time dilation
  code/modules/mob/mob.dm
Labels: quality of life

#1199 Gives Dredge the Athletics Skill
  code/modules/jobs/job_types/adventurer/types/combat/dredge.dm
Labels: balance

#1210 Adds kitchen to bandit camp
  _maps/map_files/generic/CentCom.dmm
Labels: Mapping

#1197 Ports darkest dungeon stress indicators
  code/__DEFINES/mob_timers.dm
  code/__DEFINES/traits.dm
  code/datums/ai/targetting_datum/simpe_targetting_datum.dm
  code/datums/rituals/ritual_runes.dm
  code/datums/sleep_advancement.dm
  code/game/alternate_appearance.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/keyrings.dm
  code/modules/mob/living/carbon/stress.dm
  code/modules/mob/living/living_descriptors.dm
  code/modules/mob/living/overhead_effects.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
  code/modules/spells/spell_types/wizard/utility/shadow_step.dm
  icons/mob/overhead_effects.dmi
  sound/ddrelief.ogg
  sound/ddstress.ogg
  sound/stressaffliction.ogg
  stonekeep.dme
Labels: feature, active test merge, balance, unatomized

#1209 Fixes having Accents in the native tongues
  code/__DEFINES/components.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/elf/_elf.dm
  code/modules/mob/living/carbon/human/species_types/human/_human.dm
  code/modules/mob/living/carbon/human/species_types/other/aasimar.dm
  code/modules/mob/living/carbon/human/species_types/other/halfelf.dm
  code/modules/mob/living/carbon/human/species_types/other/halforc.dm
  code/modules/mob/living/carbon/human/species_types/other/tiefling.dm
Labels: active test merge

#1158 Vanderlin Map | Map changes to the keep and garrison.
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/keys.dm
  code/game/objects/structures/mineral_doors.dm
Labels: active test merge, Mapping

#1203 Dwarven accent overhaul
  code/modules/mob/living/carbon/human/species_types/dwarf/dwarfm.dm
  strings/dwarf_replacement.json
Labels: active test merge

#1183 Another round of ports
  code/__DEFINES/colors.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/datums/components/storage/new_storage/tetris.dm
  code/datums/components/storage/storage_types.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/status_effects/rogue/debuff.dm
  code/datums/stress/negative_events.dm
  code/datums/stress/neutral_events.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/effect_system/effects_smoke.dm
  code/game/objects/items/bombs.dm
  code/game/objects/items/coins.dm
  code/game/objects/items/dmusicbox.dm
  code/game/objects/items/natural/clothfibersthorn.dm
  code/game/objects/items/perfume.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/game/turfs/open/floor.dm
  code/modules/client/preferences.dm
  code/modules/clothing/belt/misc.dm
  code/modules/clothing/gloves/leather.dm
  code/modules/clothing/head/_head.dm
  code/modules/clothing/head/god_hats.dm
  code/modules/clothing/shirts/dress.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/misc.dm
  code/modules/clothing/wrists/bracer.dm
  code/modules/cooking/raw/NeuFood_dough.dm
  code/modules/crafting/alchemy/reagents.dm
  code/modules/crafting/artificer/misc.dm
  code/modules/crafting/quality_of_crafting/_base.dm
  code/modules/crafting/quality_of_crafting/bombs.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/crafting/slapcrafting/steps/give_item.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/dead/body_markings/body_markings.dm
  code/modules/mob/dead/new_player/sprite_accessories.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/grabbing.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
  code/modules/reagents/reagent_containers/bottles/_bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/spells/spell_types/ethereal_jaunt.dm
  code/modules/spells/spell_types/wizard/utility/prestidigitation.dm
  code/modules/surgery/organs/organ_internal.dm
  icons/mob/body_markings/other_markings.dmi
  icons/roguetown/clothing/onmob/back_l.dmi
  icons/roguetown/clothing/storage.dmi
  icons/roguetown/items/food.dmi
  icons/roguetown/items/misc.dmi
  icons/roguetown/mob/hair.dmi
  modular/Barding/code/Barding_instruments.dm
  sound/items/smokebomb.ogg
Labels: active test merge

#1221 Updates Several job tutorial tooltips, removes merchants nobility, makes the sheltered heir and inbred heir virgins
  code/modules/jobs/job_types/apprentices/prince.dm
  code/modules/jobs/job_types/church/templar.dm
  code/modules/jobs/job_types/garrison/mayor.dm
  code/modules/jobs/job_types/garrison/royalguard.dm
  code/modules/jobs/job_types/garrison/veteran.dm
  code/modules/jobs/job_types/nobility/archivist.dm
  code/modules/jobs/job_types/nobility/lord.dm
  code/modules/jobs/job_types/nobility/magician.dm
  code/modules/jobs/job_types/nobility/merchant.dm
  code/modules/jobs/job_types/peasants/butler.dm
  code/modules/jobs/job_types/serfs/matron.dm
  code/modules/jobs/jobs.dm
Labels: removal

#1163 Reimplements platforms, and the Chiseling
  _maps/map_files/matthios_tomb/room/TownRuins.dmm
  _maps/map_files/matthios_tomb/room/fightingpit.dmm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/flags.dm
  code/_onclick/click.dm
  code/datums/components/crafting/crafting.dm
  code/datums/rotational_speed_data.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/cup.dm
  code/game/objects/items/natural/glass.dm
  code/game/objects/items/natural/stones.dm
  code/game/objects/items/natural/wood.dm
  code/game/objects/items/tools/chisel.dm
  code/game/objects/items/tools/hammer.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/melee/knives.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/redstone.dm
  code/game/objects/structures/rogueflora.dm
  code/game/objects/structures/trench.dm
  code/game/turfs/open/_open.dm
  code/game/turfs/open/floor.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/game/turfs/turf.dm
  code/modules/antagonists/villain/zizocult.dm
  code/modules/crafting/anvil_recipes/tools.dm
  code/modules/crafting/quality_of_crafting/_base.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/crafting/quality_of_crafting/engineering.dm
  code/modules/crafting/quality_of_crafting/fishing.dm
  code/modules/crafting/quality_of_crafting/natural_items.dm
  code/modules/crafting/slapcrafting/_slapcraft_assembly.dm
  code/modules/crafting/slapcrafting/_slapcraft_living.dm
  code/modules/crafting/slapcrafting/_slapcrafting_recipe.dm
  code/modules/crafting/slapcrafting/_slapcrafting_step.dm
  code/modules/crafting/slapcrafting/recipes/masonry/statues.dm
  code/modules/crafting/slapcrafting/steps/_abstract_steps.dm
  code/modules/crafting/slapcrafting/steps/add_to_structure.dm
  code/modules/crafting/slapcrafting/steps/give_item.dm
  code/modules/crafting/slapcrafting/steps/use_items.dm
  code/modules/crafting/turfs.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/mason.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/Lmason.dm
  code/modules/jobs/job_types/serfs/artificer.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  icons/mob/roguehud.dmi
  icons/obj/objects.dmi
  icons/roguetown/items/natural.dmi
  icons/roguetown/misc/ay.dmi
  icons/roguetown/misc/tallstructure.dmi
  icons/roguetown/onmob/lefthand.dmi
  icons/roguetown/onmob/righthand.dmi
  icons/roguetown/weapons/tools.dmi
  stonekeep.dme
Labels: feature, fix, active test merge, balance, Mapping, Sprites

#1251 Hidden Door Unmeta but we're doing it again
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/structures/hidden_doors.dm
Labels: Mapping

#1053 Access helpers replacement and key adjustments
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/access.dm
  code/game/objects/items/keyrings.dm
  code/game/objects/items/keys.dm
  code/game/objects/structures/fake_machines/vendor.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/pillory.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/physicker.dm
  code/modules/jobs/job_types/apprentices/squire.dm
  code/modules/jobs/job_types/church/adept.dm
  code/modules/jobs/job_types/garrison/royalguard.dm
  code/modules/jobs/job_types/nobility/feldsher.dm
  code/modules/jobs/job_types/nobility/nightman.dm
  code/modules/jobs/job_types/peasants/bathmaid.dm
  code/modules/jobs/job_types/serfs/artificer.dm
  code/modules/jobs/job_types/serfs/blacksmith.dm
  code/modules/jobs/job_types/serfs/physicker.dm
  code/modules/jobs/job_types/serfs/tailor.dm
  code/modules/mapping/mapping_helpers/access_helper.dm
Labels: Mapping

#1217 Psydon lore
  code/datums/gods/_patron.dm
  code/datums/gods/faiths/forgotten.dm
  code/datums/gods/patrons/forgotten.dm
  code/modules/admin/verbs/pray.dm
  code/modules/client/preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/paladin.dm
Labels: feature

#1271 Elves now say "Stewert" instead of "Steward"
  strings/russian_replacement.json
Labels: tweak

#1226 Deadmin toggles Hearsall off
  code/modules/admin/admin_verbs.dm
Labels: test merge, quality of life, administration

#1247 log defense will be added to the attacker's logs too
  code/game/atoms.dm
Labels: logging
