Repository Monkestation/Vanderlin, pull requests merged in 2025-02, with the labels that each got.

#732 (FLAIRE) Slightly changes Roundend texts
  code/__HELPERS/roundend.dm
Labels: tweak

#735 (MISC) Allow Aasimars to be Captains.
  code/modules/jobs/job_types/roguetown/nobility/captain.dm
Labels: tweak

#722 Tailor Shop Changes (And minor merchant changes)
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/items/rogueitems/keyrings.dm
  code/game/objects/items/rogueitems/keys.dm
Labels: quality of life

#740 (MUSIC) Changes Sleeping Music
  sound/music/area/sleeping.ogg
Labels: tweak

#719 (SOUND) Adds a bunch of generic mechanical sounds.
  sound/foley/industrial/clunk.ogg
  sound/foley/industrial/loadin.ogg
  sound/foley/industrial/loadout.ogg
  sound/foley/industrial/machinechug.ogg
  sound/foley/industrial/machineoff.ogg
  sound/foley/industrial/pneumatic1.ogg
  sound/foley/industrial/pneumatic2.ogg
  sound/foley/industrial/pneumaticclose.ogg
  sound/foley/industrial/pneumatichiss.ogg
  sound/foley/industrial/pneumaticpop.ogg
  sound/foley/industrial/pneumaticpop2.ogg
  sound/foley/industrial/pneumaticpress.ogg
  sound/foley/industrial/pneumaticshort1.ogg
  sound/foley/industrial/pneumaticshort2.ogg
  sound/foley/industrial/rollingclicks.ogg
  sound/foley/industrial/rollingmachine.ogg
  sound/foley/industrial/toggle.ogg
Labels: feature

#667 Bugfixing Hodgepodge 1 (Heater Craft, PEDDLER Rotting, Kettle Eyeslits, Chicken Nest Farming, Apothecary Gold)
  _maps/map_files/vanderlin/vanderlin.dmm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/living/simple_animal/rogue/farm/chicken.dm
  code/modules/roguetown/roguecrafting/quality_of_crafting/crafting.dm
Labels: fix, active test merge

#695 Instrument refactor
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/processing/persecond.dm
  code/controllers/subsystem/rogue/devotion.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/datums/stress/positive_events.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/antagonists/roguetown/villain/zomble.dm
  code/modules/jobs/job_types/roguetown/apprentices/servant.dm
  code/modules/mob/living/carbon/rogfatstam.dm
  code/modules/roguetown/roguecrafting/alchemy/reagents.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/armor.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/valuables.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/weapons.dm
  modular/Barding/code/Barding_instruments.dm
  modular/Barding/code/music_effect.dm
  sound/instruments/flute (9).ogg
  sound/instruments/guitar (17).ogg
  sound/instruments/guitar (18).ogg
  sound/instruments/guitar (19).ogg
  sound/instruments/guitar (20).ogg
  stonekeep.dme
Labels: active test merge, code maintenance

#761 Creates a Middlewear for Elasticsearch for better data gathering
  code/__HELPERS/auxtools.dm
  code/__HELPERS/time.dm
  code/controllers/subsystem/elastic.dm
  code/controllers/subsystem/rogue/death_arena.dm
  code/datums/ai/behaviours/eat_food/eat_body.dm
  code/datums/components/crafting/crafting.dm
  code/game/machinery/trams_and_elevators/lift_master.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/closed/wall/roguewalls.dm
  code/modules/error_handler/error_handler.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  code/modules/underworld/underworld.dm
  stonekeep.dme
Labels: feature, active test merge, administration

#795 (FIX/BALANCE) Lower STR requirement for wooden staff by 1 (MAGES IN AWE)
  code/game/objects/items/rogueweapons/melee/polearms.dm
Labels: balance

#783 [BugFix] Fix legcuffs not working at all
  code/__DEFINES/movespeed_modification.dm
  code/datums/status_effects/rogue/debuff.dm
  code/game/objects/items/rogueitems/ropechainbola.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
Labels: fix, active test merge

#661 (MIGRANT) Adds Daywalkers, Bane of Deadites
  code/datums/migrants/waves/daywalker.dm
  stonekeep.dme
Labels: feature, active test merge

#821 SOUND: New title music
  code/controllers/subsystem/ticker.dm
  sound/music/credits.txt
  sound/music/title3.ogg
Labels: Sound, Music

#830 Major lankmark changing.
  _maps/map_files/generic/CentCom.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_bog.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_forest.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_mountain.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_mountain.json
  _maps/map_files/vanderlin/vanderlin.dmm
  code/controllers/subsystem/mapping.dm
Labels: Mapping

#829 Adds Sea Shanty 2 to instruments
  modular/Barding/code/Barding_instruments.dm
  sound/instruments/band/flute (b1).ogg
  sound/instruments/band/harp (b1).ogg
  sound/instruments/band/lute (b1).ogg
  sound/instruments/band/viola (b1).ogg
  sound/music/credits.txt
Labels: feature, Sound, Music

#789 A big mess of stuff
  code/_onclick/hud/screen_objects.dm
  code/datums/character_flaw/_character_flaw.dm
  code/datums/components/storage/new_storage/tetris.dm
  code/datums/mind.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/rogueitems/gems.dm
  code/game/objects/items/rogueitems/keys.dm
  code/game/objects/items/rogueweapons/ranged/ammo.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/roguetown/redstone.dm
  code/modules/client/verbs/ghost.dm
  code/modules/clothing/rogueclothes/hats.dm
  code/modules/clothing/rogueclothes/pants.dm
  code/modules/clothing/rogueclothes/quiver.dm
  code/modules/clothing/rogueclothes/shirts.dm
  code/modules/jobs/job_types/roguetown/adventurer/types/combat/amazon.dm
  code/modules/jobs/job_types/roguetown/church/templar.dm
  code/modules/jobs/job_types/roguetown/garrison/garrisonguard.dm
  code/modules/jobs/job_types/roguetown/garrison/men_at_arms.dm
  code/modules/jobs/job_types/roguetown/peasants/jester.dm
  code/modules/jobs/job_types/roguetown/peasants/miner.dm
  code/modules/jobs/job_types/roguetown/serfs/carpenter.dm
  code/modules/library/lib_items.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/rogue/creacher/bigrat.dm
  code/modules/mob/living/simple_animal/rogue/game/saiga.dm
  code/modules/mob/living/simple_animal/rogue/rogueanimals.dm
  code/modules/roguetown/roguecrafting/quality_of_crafting/crafting.dm
  code/modules/roguetown/roguecrafting/quality_of_crafting/leatherworking.dm
  code/modules/roguetown/roguecrafting/quality_of_crafting/sewing.dm
  code/modules/roguetown/roguejobs/artifcier/contraption.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/_anvil_recipe.dm
  code/modules/roguetown/roguejobs/blacksmith/anvil_recipes/tools.dm
  code/modules/roguetown/roguejobs/blacksmith/tools.dm
  code/modules/roguetown/roguejobs/gravedigger/hole.dm
  code/modules/spells/roguetown/acolyte/astrata.dm
  code/modules/spells/roguetown/acolyte/pestra.dm
  icons/mob/screen_gen.dmi
  icons/roguetown/clothing/onmob/shirts.dmi
  icons/roguetown/clothing/shirts.dmi
  icons/roguetown/weapons/ammo.dmi
  modular/Barding/code/Barding_instruments.dm
Labels: feature, fix, active test merge, balance, unatomized

#839 Matthios Dungeon Addition
  _maps/map_files/matthios_tomb/room/AcidMageTower.dmm
  _maps/map_files/matthios_tomb/room/Thelastbreath.dmm
  code/datums/dungeon_generator/dungeon_templates/rooms/common.dm
Labels: feature, Mapping

#859 Removes Unused Reagents
  code/datums/blood_types.dm
  code/datums/brewing_recipes/brandy.dm
  code/datums/brewing_recipes/cabbage.dm
  code/datums/brewing_recipes/cider.dm
  code/datums/brewing_recipes/jacksberry_mix.dm
  code/datums/brewing_recipes/onion_beer.dm
  code/datums/brewing_recipes/vodden.dm
  code/datums/rotational_speed_data.dm
  code/game/objects/effects/decals/cleanable/misc.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/soap.dm
  code/game/objects/pipe_system.dm
  code/game/rotational_objects/fluid_objects/boiler.dm
  code/modules/events/vines.dm
  code/modules/farming/fermentation_keg.dm
  code/modules/food_and_drinks/food/condiments.dm
  code/modules/food_and_drinks/recipes/food_mixtures.dm
  code/modules/hydroponics/plant_genes.dm
  code/modules/mob/living/bloodcrawl.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/paperwork/paper.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/drug_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/reagents/chemistry/reagents/medicine_reagents.dm
  code/modules/reagents/chemistry/reagents/other_reagents.dm
  code/modules/reagents/chemistry/reagents/toxin_reagents.dm
  code/modules/reagents/chemistry/recipes/drugs.dm
  code/modules/reagents/chemistry/recipes/medicine.dm
  code/modules/reagents/chemistry/recipes/others.dm
  code/modules/reagents/chemistry/recipes/pyrotechnics.dm
  code/modules/reagents/chemistry/recipes/special.dm
  code/modules/reagents/chemistry/recipes/toxins.dm
  code/modules/reagents/reagent_containers/bottles/_bottle.dm
  code/modules/reagents/reagent_containers/bottles/alchemy.dm
  code/modules/reagents/reagent_containers/carafe.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/spells/spell_types/invoked/acolyte/eora.dm
  code/modules/surgery/organs/liver.dm
  stonekeep.dme
Labels: Mapping, removal

#851 Matthios Maps 2
  _maps/map_files/matthios_tomb/room/Goonies.dmm
  _maps/map_files/matthios_tomb/room/SmithRest.dmm
  code/datums/dungeon_generator/dungeon_templates/rooms/common.dm
Labels: Mapping

#703 Fish Sprite updates
  icons/roguetown/misc/fish.dmi
Labels: feature, active test merge, Sprites

#865 Adminned clients will not get the death hud, view range adjustments
  code/__DEFINES/misc.dm
  code/_onclick/hud/ghost.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/dead/observer/observer.dm
Labels: fix, administration

#835 Powder only deletes on throw when sniffed
  code/modules/reagents/reagent_containers/powderspice.dm
Labels: tweak

#846 Adds 2 new tomb rooms. Also allows certain rooms to spawn.
  _maps/map_files/matthios_tomb/room/hctomb1.dmm
  _maps/map_files/matthios_tomb/room/hctomb2.dmm
  _maps/map_files/matthios_tomb/room/hctomb3.dmm
  _maps/map_files/matthios_tomb/room/hctomb4.dmm
  _maps/map_files/matthios_tomb/room/hctomb5.dmm
  code/datums/dungeon_generator/dungeon_templates/rooms/common.dm
Labels: Mapping

#803 Random potion colors every round (METAGAMERS HATE THIS PR!)
  code/_globalvars/lists/objects.dm
  code/modules/crafting/alchemy/reagents.dm
  code/modules/reagents/chemistry/colors.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
Labels: active test merge, balance

#793 Smells and Scents
  code/game/atoms.dm
  code/modules/crafting/alchemy/reagents.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
Labels: feature

#868 Fixing dungeon maps
  _maps/map_files/matthios_tomb/entry/Tented Entrance.dmm
  _maps/map_files/matthios_tomb/entry/eastentrance.dmm
  _maps/map_files/matthios_tomb/hallway/Puzzle Trap Large.dmm
  _maps/map_files/matthios_tomb/hallway/Puzzle Trap Medium.dmm
  _maps/map_files/matthios_tomb/hallway/Puzzle Trap Small.dmm
  _maps/map_files/matthios_tomb/hallway/Wild Dungeon Medium.dmm
  _maps/map_files/matthios_tomb/hallway/Wild Dungeon Small.dmm
  _maps/map_files/matthios_tomb/hallway/lampternhallway.dmm
  _maps/map_files/matthios_tomb/rest/snackplatter.dmm
  _maps/map_files/matthios_tomb/room/AcidMageTower.dmm
  _maps/map_files/matthios_tomb/room/Allbutwesthall.dmm
  _maps/map_files/matthios_tomb/room/Bathhouse Dungeon.dmm
  _maps/map_files/matthios_tomb/room/DarkCorridors.dmm
  _maps/map_files/matthios_tomb/room/ForgottenInn.dmm
  _maps/map_files/matthios_tomb/room/GoblinInfestedJoint.dmm
  _maps/map_files/matthios_tomb/room/Goonies.dmm
  _maps/map_files/matthios_tomb/room/Lava Medium.dmm
  _maps/map_files/matthios_tomb/room/Lava Small.dmm
  _maps/map_files/matthios_tomb/room/Thelastbreath.dmm
  _maps/map_files/matthios_tomb/room/TownRuins.dmm
  _maps/map_files/matthios_tomb/room/acidfight.dmm
  _maps/map_files/matthios_tomb/room/drugden.dmm
  _maps/map_files/matthios_tomb/room/fightpit.dmm
  _maps/map_files/matthios_tomb/room/goblincamp.dmm
  _maps/map_files/matthios_tomb/room/graveend.dmm
  _maps/map_files/matthios_tomb/room/hctomb1.dmm
  _maps/map_files/matthios_tomb/room/queensretreat.dmm
  _maps/map_files/matthios_tomb/room/skeletonroom.dmm
  _maps/map_files/matthios_tomb/room/small lab.dmm
  icons/turf/floors.dmi
Labels: Mapping
