Repository Monkestation/Vanderlin, pull requests merged in 2025-09, with the labels that each got.

#3106 Plexora announce
  code/controllers/subsystem/plexora.dm
Labels: Code Maintenance

#3097 Fixes Assassins Beggar and Servants still being foreigners
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/types/combat/rare/assassin.dm
Labels: Fix

#2781 (almost) ALL CLOTHES CRAFTABLE part 2
  _maps/map_files/shared/CentCom.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/whitepalacepass/WhitePalacePass.dmm
  _maps/matthios_tomb/room/Pit.dmm
  _maps/matthios_tomb/room/SteamCastle.dmm
  _maps/matthios_tomb/unusable/SpiderPit.dmm
  code/datums/components/loot_spawner/loot_tables/generics.dm
  code/datums/migrants/waves/grenzelhoft_wave.dm
  code/datums/migrants/waves/prisoner_wave.dm
  code/datums/world_factions/coastal.dm
  code/datums/world_factions/zalad.dm
  code/game/objects/items/cigs_lighters.dm
  code/modules/antagonists/villain/maniac/_maniac.dm
  code/modules/antagonists/villain/maniac/fake_world.dm
  code/modules/antagonists/villain/vampire/objects/bloodpool.dm
  code/modules/cargo/supply_packs/jewelry.dm
  code/modules/cargo/supply_packs/luxury.dm
  code/modules/clothing/armor/cuirass.dm
  code/modules/clothing/armor/medium.dm
  code/modules/clothing/armor/misc.dm
  code/modules/clothing/armor/rare.dm
  code/modules/clothing/cloak/cape.dm
  code/modules/clothing/cloak/solider_tabard.dm
  code/modules/clothing/gloves/rare.dm
  code/modules/clothing/head/crown.dm
  code/modules/clothing/head/helmets/heavy.dm
  code/modules/clothing/head/helmets/misc.dm
  code/modules/clothing/head/rare.dm
  code/modules/clothing/ring/misc.dm
  code/modules/clothing/shirts/dress.dm
  code/modules/clothing/shirts/robe.dm
  code/modules/clothing/shoes/misc.dm
  code/modules/clothing/shoes/rare.dm
  code/modules/clothing/wrists/misc.dm
  code/modules/crafting/anvil_recipes/armor.dm
  code/modules/crafting/anvil_recipes/valuables.dm
  code/modules/crafting/artificer/misc.dm
  code/modules/crafting/quality_of_crafting/leatherworking.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/grenzelhoft.dm
  code/modules/jobs/job_types/apprentices/squire.dm
  code/modules/jobs/job_types/garrison/dungeoneer.dm
  code/modules/jobs/job_types/garrison/veteran.dm
  code/modules/jobs/job_types/nobility/captain.dm
  code/modules/jobs/job_types/other/deathknight.dm
  code/modules/jobs/job_types/other/merc_classes/blackoak.dm
  code/modules/jobs/job_types/other/merc_classes/grenzelhoft.dm
  code/modules/unit_tests/craftable_clothes.dm
  tools/UpdatePaths/Scripts/2781_more_recipes_followup.txt
Labels: Feature, Mapping

#2982 Rakshari Changes
  code/__DEFINES/sound.dm
  code/__DEFINES/traits.dm
  code/_globalvars/special_traits/traits.dm
  code/_globalvars/traits.dm
  code/game/say.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species_types/rakshari/_rakshari.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living_say.dm
  code/modules/surgery/organs/external/ears.dm
  sound/vo/cat/attribution.txt
  sound/vo/cat/cat_meow1.ogg
  sound/vo/cat/cat_meow2.ogg
  sound/vo/cat/cat_meow3.ogg
  sound/vo/cat/cat_purr1.ogg
  sound/vo/cat/cat_purr2.ogg
  sound/vo/cat/cat_purr3.ogg
  sound/vo/cat/cat_purr4.ogg
  sound/vo/cat/oranges_meow1.ogg
Labels: Feature, Removal

#3098 Saw dust and stone chippings can now be cleaned by players.
  code/game/objects/effects/decals/cleanable/misc.dm
Labels: Feature

#3125 Add Catbox as a Headshot Domain
  code/modules/client/preferences/_preferences.dm
Labels: Fix

#3126 Silence!!
  code/game/atom/atoms.dm
  code/game/objects/structures/fake_machines/titan.dm
  code/modules/mob/living/living.dm
  icons/effects/32x48.dmi
Labels: Feature, Fix

#3121 Animation features fixes
  code/datums/locks/lock_access.dm
  code/game/atom/atoms_movable.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix

#3084 Silver Changes
  code/game/objects/items/coins.dm
  code/game/objects/items/ore.dm
  code/game/objects/items/plate.dm
  code/game/objects/items/statue.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/modules/antagonists/villain/werewolf/werewolf.dm
  code/modules/antagonists/villain/zizocult.dm
  code/modules/clothing/armor/plate.dm
  code/modules/clothing/belt/misc.dm
  code/modules/clothing/face/masks.dm
  code/modules/clothing/head/helmets/heavy.dm
  code/modules/clothing/head/helmets/misc.dm
  code/modules/clothing/pants/plate_legs.dm
  code/modules/clothing/ring/misc.dm
  code/modules/mob/living/grabbing.dm
  code/modules/spells/spell_types/undirected/transfix.dm
Labels: Feature, Test Merge

#3131 Add basic toggle pref functionality to the prefs page
  code/__DEFINES/preferences.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/subsystem/ambience.dm
  code/datums/browser/modal/input/input_list.dm
  code/modules/antagonists/villain/maniac/maniac_life.dm
  code/modules/balloon_alert/balloon_alert.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/client/preferences/preferences_savefile.dm
  code/modules/mob/dead/observer/observer_say.dm
  code/modules/mob/living/living_say.dm
Labels: Feature

#3146 Fix Mirrors to Change Hair Color Again
  code/game/objects/structures/mirror.dm
Labels: Fix

#3149 apparently vis contents play bad with plane master
  code/_onclick/drag_drop.dm
  code/_onclick/hud/plane_master.dm
  code/datums/beam.dm
  code/datums/mana/leylines/_leyline.dm
  code/modules/admin/holder2.dm
Labels: Fix

#3152 just remove the damn vent from vanderlin
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/rotational_objects/fluid_objects/water_vent.dm
Labels: Fix, Mapping, Removal

#3119 Animated runechat messages
  code/__DEFINES/chat.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/split_string_to_list.dm
  code/_globalvars/traits.dm
  code/datums/chatmessage.dm
  code/game/objects/structures/fake_machines/scomm.dm
  code/game/sound.dm
  code/modules/jobs/job_types/peasants/jester.dm
  sound/effects/chat_toots/toot1.ogg
  sound/effects/chat_toots/trombone_toot2.ogg
  vanderlin.dme
Labels: Feature

#3122 Add four new type of godless
  code/datums/gods/faiths/atheism.dm
  code/datums/gods/patrons/atheism.dm
  code/modules/antagonists/villain/vampire/lord.dm
  code/modules/jobs/job_types/church/inquisitor.dm
  code/modules/spells/spell_types/pointed/healing.dm
Labels: Feature

#3171 Tabard Fix
  code/modules/crafting/quality_of_crafting/sewing.dm
Labels: Fix

#2987 Quickbag
  code/datums/keybinding/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Feature

#3117 Harpoon gun is craftable
  code/modules/crafting/artificer/misc.dm
Labels: Feature

#3150 Sprites for steel and iron gears
  code/game/objects/items/gear.dm
  icons/roguetown/items/new_gears.dmi
Labels: Feature

#3196 Fix being unable to turn off all toggle options
  code/modules/client/preferences/_preferences.dm
Labels: Fix

#3137 Peddlers hawk their wares
  code/game/objects/structures/fake_machines/vendor.dm
Labels: Feature, Code Maintenance

#3203 Fixes "Ultimate Sacrifice" spell
  code/modules/spells/spell_types/pointed/ultimate_sacrifice.dm
Labels: Fix

#3013 Accent Changes
  code/datums/migrants/waves/crusader_wave.dm
  code/datums/migrants/waves/grenzelhoft_wave.dm
  code/datums/migrants/waves/zalad_wave.dm
  code/modules/antagonists/villain/lich/lich.dm
  code/modules/antagonists/villain/zomble.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/swordmaster.dm
  code/modules/jobs/job_types/adventurer/types/combat/rare/freelancer.dm
  code/modules/jobs/job_types/adventurer/types/combat/rare/qatil.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/grenzelhoft.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/preacher.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/zalad.dm
  code/modules/jobs/job_types/adventurer/types/special/crusader.dm
  code/modules/jobs/job_types/church/inquisitor.dm
  code/modules/jobs/job_types/other/merc_classes/grenzelhoft.dm
  code/modules/jobs/job_types/other/merc_classes/zalad.dm
  code/modules/jobs/job_types/other/skeleton.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/dwarf/_dwarf.dm
  code/modules/mob/living/carbon/human/species_types/dwarf/dwarfm.dm
  code/modules/mob/living/carbon/human/species_types/elf/_elf.dm
  code/modules/mob/living/carbon/human/species_types/elf/elfd.dm
  code/modules/mob/living/carbon/human/species_types/elf/elfs.dm
  code/modules/mob/living/carbon/human/species_types/human/_human.dm
  code/modules/mob/living/carbon/human/species_types/other/aasimar.dm
  code/modules/mob/living/carbon/human/species_types/other/halfdrow.dm
  code/modules/mob/living/carbon/human/species_types/other/halfelf.dm
  code/modules/mob/living/carbon/human/species_types/other/halforc.dm
  code/modules/mob/living/carbon/human/species_types/other/tiefling.dm
  code/modules/mob/living/carbon/human/species_types/rakshari/_rakshari.dm
  code/modules/mob/living/carbon/human/species_types/triton/_triton.dm
Labels: Code Maintenance

#3205 Fix ultimate sacrifice args
  code/modules/spells/spell_types/pointed/ultimate_sacrifice.dm
Labels: Fix

#3115 Steam knight slop
  code/modules/jobs/job_types/garrison/royal_knight.dm
Labels: Balance

#3116 Steam knight armour slop
  code/modules/clothing/armor/steam.dm
  code/modules/clothing/cloak/steam.dm
  code/modules/clothing/gloves/steam.dm
  code/modules/clothing/head/helmets/steam.dm
  code/modules/clothing/shoes/steam.dm
  code/modules/crafting/artificer/misc.dm
Labels: Feature, Balance

#3247 Punches can do wounds and crits again
  code/modules/mob/living/living_wounds.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Fix

#3259 No take backs on round end vote
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
Labels: Fix

#3271 Harpies have wings and right tail in species organs
  code/modules/mob/living/carbon/human/species_types/harpy/_harpy.dm
Labels: Fix

#3230 Watchmen stomping noise boots
  code/__DEFINES/sound.dm
  code/game/sound.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/crafting/quality_of_crafting/leatherworking.dm
  code/modules/jobs/job_types/garrison/garrisonguard.dm
  sound/foley/footsteps/armor/heavy-footstep (1).ogg
  sound/foley/footsteps/armor/heavy-footstep (2).ogg
  sound/foley/footsteps/armor/heavy-footstep (3).ogg
  sound/foley/footsteps/armor/heavy-footstep (4).ogg
  sound/foley/footsteps/armor/heavy-footstep (5).ogg
Labels: Feature, Sound

#3144 Dice cups
  code/game/objects/items/dice.dm
  code/game/objects/items/dice_cup.dm
  code/modules/crafting/anvil_recipes/tools.dm
  code/modules/crafting/quality_of_crafting/generic.dm
  icons/obj/dice.dmi
  vanderlin.dme
Labels: Feature

#3240 Examine Miniature
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#3195 Wicker handbaskets
  code/datums/components/storage/storage_grid_types.dm
  code/game/objects/items/bags.dm
  code/modules/crafting/quality_of_crafting/natural_items.dm
  icons/roguetown/items/misc.dmi
Labels: Feature, Code Maintenance

#3224 Two new wretch subclasses: Rejected Royal and Rouschild
  code/modules/jobs/job_types/adventurer/types/wretch/reject.dm
  code/modules/jobs/job_types/adventurer/types/wretch/rouschild.dm
  code/modules/spells/spell_types/pointed/conjure/rous.dm
  vanderlin.dme
Labels: Feature

#3311 Removes something in the code that was absolutely not supposed to be there.
  code/__DEFINES/mobs.dm
Labels: Code Maintenance, Removal, FUCK

#3261 Fix spacedrugs not getting you get high
  code/_onclick/hud/plane_master.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/objects/items/cigs_lighters.dm
Labels: Fix

#3302 Renegade is Grenz!.dm
  code/modules/jobs/job_types/adventurer/types/wretch/vigilante.dm
Labels: Code Maintenance

#3213 Phantom Ear: Eavesdropping Spell
  code/datums/stress/negative_events.dm
  code/game/objects/items/phantom_ear.dm
  code/modules/spells/_spell_tree/circular_tree.dm
  code/modules/spells/spell_types/pointed/conjure/phantom_ear.dm
  icons/Phantom_Ear_Icon.dmi
  icons/mob/actions/roguespells.dmi
  icons/roguetown/misc/phantomear.dmi
  vanderlin.dme
Labels: Feature, Code Maintenance, Sprites

#3336 Revert crits requiring a wound to be added
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Fix

#3201 the Lakkarian Cleric
  code/modules/clothing/armor/gambesson.dm
  code/modules/clothing/head/helmets/misc.dm
  code/modules/clothing/pants/trousers.dm
  code/modules/crafting/anvil_recipes/armor.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/jobs/job_types/adventurer/types/combat/rare/lakkariancleric.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_pants.dmi
  icons/roguetown/clothing/onmob/pants.dmi
  icons/roguetown/clothing/pants.dmi
  vanderlin.dme
Labels: Feature, Sprites

#3308 Animated runechat tweaks
  code/datums/chatmessage.dm
  code/game/objects/structures/fake_machines/scomm.dm
Labels: Quality of Life

#3260 Diagondiagonally movement
  code/datums/components/item_equipped_movement_rustle.dm
  code/datums/elements/footstep.dm
  code/game/atom/atoms_movable.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/mob/mob_movement.dm
Labels: Feature

#3340 Map changes
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#3379 Testing project add workflow
  .github/workflows/add_issue_to_project.yml
Labels: Github

#3369 Remaps courtphys room
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#3370 Updates wizard tower alchemy lab
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#3372 removes the cannon from vanderlin
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping, Removal

#3361 Veteran home gets a little love
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#3064 Various Admin requests
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/migration.dm
  code/controllers/subsystem/particle_weather.dm
  code/datums/migrants/migrant_pref.dm
  code/datums/particle_weathers/_base.dm
  code/datums/particle_weathers/datum_types/snow_storm.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/migration.dm
  vanderlin.dme
Labels: Fix, Administration

#3253 Steamknight Armor Toggle Refactor
  code/datums/components/steam_storage.dm
  code/datums/migrants/waves/heartfell_wave.dm
  code/game/rotational_objects/fluid_objects/steam_recharger.dm
  code/modules/clothing/armor/steam.dm
  code/modules/clothing/cloak/steam.dm
  code/modules/clothing/gloves/steam.dm
  code/modules/clothing/head/helmets/steam.dm
  code/modules/clothing/shoes/steam.dm
  code/modules/jobs/job_types/garrison/royal_knight.dm
Labels: Code Maintenance, Quality of Life

#3331 New dungeoneer sack hood + Tower shield heraldies
  code/modules/clothing/head/misc.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/jobs/job_types/garrison/dungeoneer.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/weapons/shield_heraldry.dmi
Labels: Feature, Sprites

#3390 Change reagent cycling to alt click and let it work...
  code/modules/reagents/reagent_containers.dm
Labels: Fix

#3332 Fix the Werewolf Younglig sprite not appearing even for Younglings who turned into a werewolf
  code/modules/antagonists/villain/werewolf/werewolf_transformation.dm
Labels: Fix

#3410 Rosewood Inn Rolling Pin
  _maps/map_files/rosewood/rosewood.dmm
Labels: Code Maintenance, Mapping

#3420 Fix the Vault key not opening the Storage and their respective doors
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Fix, Mapping

#3364 Removes church key from adept keyrings
  code/game/objects/items/keyrings.dm
  code/modules/jobs/job_types/church/adept.dm
Labels: Balance, Removal

#3378 Vampire armor consistency changes
  code/modules/antagonists/villain/vampire/objects/bloodpool.dm
  code/modules/clothing/armor/chainmail.dm
  code/modules/clothing/armor/plate.dm
  code/modules/clothing/gloves/chain.dm
  code/modules/clothing/head/helmets/heavy.dm
Labels: Feature, Balance, Removal

#3386 Rashan-Kahl
  code/datums/gods/_patron.dm
  code/datums/gods/patrons/atheism.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/jobs/job_types/church/inquisitor.dm
Labels: Feature

#3426 Fixes a few bugs related to zizo worshipper not getting CABAL trait
  code/game/objects/items/weapons/melee/godweapons.dm
  code/modules/mob/living/death.dm
Labels: Fix

#3337 Sewing skill for Fishers
  code/modules/jobs/job_types/adventurer/types/pilgrim/fisher.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/Lfish.dm
  code/modules/jobs/job_types/peasants/fisher.dm
Labels: Balance

#3167 New triton mercenaries: Abyss Guard
  code/datums/faith/devotion_subtypes.dm
  code/game/objects/items/weapons/melee/polearms.dm
  code/game/objects/structures/fake_machines/mail.dm
  code/modules/clothing/neck/mercmedal.dm
  code/modules/jobs/job_types/other/merc_classes/abyssal.dm
  code/modules/spells/spell_types/pointed/pressure.dm
  code/modules/spells/spell_types/undirected/conjure_item/summon_trident.dm
  icons/roguetown/clothing/neck.dmi
  icons/roguetown/weapons/64.dmi
  vanderlin.dme
Labels: Feature, Code Maintenance

#3220 Blacksteel Changes & Plate Tweak
  code/__DEFINES/weights.dm
  code/game/objects/lighting/smelter.dm
  code/modules/clothing/armor/plate.dm
  code/modules/clothing/armor/steam.dm
  code/modules/clothing/cloak/misc.dm
  code/modules/clothing/gloves/plate.dm
  code/modules/clothing/head/helmets/heavy.dm
  code/modules/clothing/pants/plate_legs.dm
  code/modules/clothing/shoes/boots.dm
Labels: Fix

#3246 Minor miracle changes to Pestra and Abyssor
  code/datums/faith/devotion_subtypes.dm
  code/modules/spells/spell_types/pointed/attach_bodypart.dm
  code/modules/spells/spell_types/pointed/cure_rot.dm
  code/modules/spells/spell_types/undirected/conjure_item/summon_leech.dm
  vanderlin.dme
Labels: Feature, Balance

#3461 Remove randomisation confirmation
  code/modules/client/preferences/_preferences.dm
Labels: Removal

#3400 Fix Itinerant Knight wave members not being psydonites
  code/datums/migrants/waves/itinerant_knight_wave.dm
Labels: Fix

#3479 Fixes longbow recipe
  code/modules/crafting/quality_of_crafting/crafting.dm
Labels: Fix

#3424 Old Watchtower - Minor Forest Addition
  _maps/map_files/vanderlin/vanderlin_forest.dmm
Labels: Mapping

#3463 Fixes 2 SCOMs, add another SCOM to the smith and add 2 Shylocks to the smith
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Feature, Fix, Mapping

#3481 Fixes some mercs spawning without their key
  code/modules/jobs/job_types/other/merc_classes/abyssal.dm
  code/modules/jobs/job_types/other/merc_classes/sworddancer.dm
Labels: Fix

#3470 silences the runechat runtime
  code/datums/chatmessage.dm
Labels: Fix

#3489 [Serva] Adds Starvation and Dehydration config options
  code/controllers/configuration/entries/game_options.dm
  code/datums/status_effects/rogue/debuff.dm
  code/modules/mob/living/carbon/human/species.dm
  config/game_options.txt
  icons/mob/screen_alert.dmi
Labels: Code Maintenance, Config

#3458 FIx new Godless types not counting toward Apostasy at the round end.
  code/modules/client/round_end_panel.dm
Labels: Fix

#3351 A TON OF STUFF
  code/__DEFINES/roguetown.dm
  code/datums/components/container_craft/recipes/pan/_basic_pan.dm
  code/datums/components/storage/storage_grid_types.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/natural/clothfibersthorn.dm
  code/game/objects/items/natural/wood.dm
  code/game/objects/items/needle.dm
  code/game/objects/items/ore.dm
  code/game/objects/lighting/smelter.dm
  code/modules/cooking/NeuFood.dm
  code/modules/cooking/raw/NeuFood_dough.dm
  code/modules/cooking/raw/NeuFood_processed.dm
  code/modules/cooking/raw/NeuFood_veggies.dm
  code/modules/crafting/quality_of_crafting/cooking/misc.dm
  code/modules/farming/items/produce/_produce.dm
  code/modules/mob/living/carbon/human/species_types/rakshari/_rakshari.dm
  code/modules/reagents/reagent_containers/bucket_pot.dm
Labels: Code Maintenance

#3388 Examining other people tells you their con and spd
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature

#3425 Fix a few harpoon bugs & Fix a few royal knight steam class bugs.
  code/game/objects/items/harpoon_gun.dm
  code/modules/clothing/cloak/steam.dm
  code/modules/jobs/job_types/garrison/royal_knight.dm
Labels: Fix

#3505 Fixes Magician Apprentice patron lock not working
  code/modules/jobs/job_types/apprentices/wapprentice.dm
Labels: Fix

#3373 Adds a new admin smite.
  code/__DEFINES/admin.dm
  code/datums/stress/negative_events.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration

#3533 Fixes Sallet being unforgeable
  code/modules/crafting/anvil_recipes/armor.dm
Labels: Fix

#3419 allows you to bind spacebar in keybinds [PORT]
  code/_globalvars/lists/client.dm
Labels: Code Maintenance
