Repository Monkestation/Vanderlin, pull requests merged in 2025-08, with the labels that each got.

#2619 Duplicate crown fix
  code/modules/clothing/head/crown.dm
Labels: Fix

#2592 Inhumen Miracles Fixes
  code/datums/status_effects/rogue/roguebuff.dm
  code/modules/spells/spell_types/pointed/transact.dm
  code/modules/spells/spell_types/undirected/touch/orison.dm
Labels: Feature, Fix

#2653 Cancel actions and remove processing when pawn is unpossessed
  code/datums/ai/_ai_controller.dm
Labels: Fix

#2657 Farmers get a satchel for their books
  code/modules/jobs/job_types/peasants/soilson.dm
Labels: Fix, Balance

#2662 Fixes actors menu not opening
  code/datums/browser/_browser.dm
Labels: Fix

#2671 Secret for changelog
  .github/workflows/compile_changelog.yml
Labels: Github, Logging

#2672 use vanderbot for changelogs
  .github/workflows/compile_changelog.yml
Labels: Code Maintenance, Github, Logging

#2656 Assorted balancing changes
  code/__DEFINES/plant_genetics.dm
  code/datums/components/storage/new_storage/tetris.dm
  code/datums/enchantments/silver.dm
  code/datums/outfit.dm
  code/datums/world_factions/traders/trade_component.dm
  code/game/objects/items/natural/poo.dm
  code/game/objects/structures/dock_bell.dm
  code/game/objects/structures/hole.dm
  code/game/turfs/open/water.dm
  code/modules/crafting/quality_of_crafting/books.dm
  code/modules/farming/genetics/heirlooms.dm
  code/modules/farming/genetics/plant_genetics.dm
  code/modules/farming/items/fertilizer.dm
  code/modules/farming/items/seeds.dm
  code/modules/farming/plant_def/_base.dm
  code/modules/farming/plant_def/alchemical.dm
  code/modules/farming/plant_def/allium.dm
  code/modules/farming/plant_def/brassica.dm
  code/modules/farming/plant_def/flowers.dm
  code/modules/farming/plant_def/grain.dm
  code/modules/farming/plant_def/herb.dm
  code/modules/farming/plant_def/root.dm
  code/modules/farming/plant_def/rosaceae.dm
  code/modules/farming/plant_def/rubiaceae.dm
  code/modules/farming/plant_def/rutaceae.dm
  code/modules/farming/plant_def/solanaceae.dm
  code/modules/farming/plant_def/theaceae.dm
  code/modules/farming/soil.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/spells/spell_types/pointed/ocean_embrace.dm
Labels: Balance

#2680 Ticker fix
  code/controllers/subsystem/ticker.dm
Labels: Fix

#2629 Admin book management
  code/controllers/subsystem/librarian.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client_procs.dm
  code/modules/library/lib_machines.dm
Labels: Administration

#2673 Triumph Shop: New storyteller triumph buys, fair refunds, code improvements
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/migration.dm
  code/controllers/subsystem/role_class_handler/role_class_handler.dm
  code/controllers/subsystem/triumph/buy_datums/character/pick_all_jobs_as_any_race.dm
  code/controllers/subsystem/triumph/buy_datums/character/pick_any_class.dm
  code/controllers/subsystem/triumph/buy_datums/storyteller/bonus_influence.dm
  code/controllers/subsystem/triumph/buy_datums/triumph_buy_datums.dm
  code/controllers/subsystem/triumph/triumph_buy_menu.dm
  code/controllers/subsystem/triumph/triumphs.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/types/_advclass.dm
  code/modules/mob/dead/new_player/new_player.dm
  vanderlin.dme
Labels: Feature, Quality of Life

#2570 Title screen
  code/__DEFINES/click.dm
  code/__DEFINES/dcs/signals/signals_hud.dm
  code/__DEFINES/dcs/signals/signals_subsystems.dm
  code/__DEFINES/dcs/signals/signals_ticker.dm
  code/__DEFINES/layers.dm
  code/__HELPERS/game.dm
  code/_onclick/drag_drop.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/new_player.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/ticker.dm
  code/game/atom/atoms.dm
  code/game/objects/items/books.dm
  code/game/objects/items/candle.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/rogueflora.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/crafting/alchemy/essence_machines/essence_nodes.dm
  code/modules/crafting/quality_of_crafting/books.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/paperwork/rogue.dm
  code/modules/visual_ui/_base.dm
  icons/hud/lobby/actors.dmi
  icons/hud/lobby/background.dmi
  icons/hud/lobby/character_sheet.dmi
  icons/hud/lobby/collapse_expand.dmi
  icons/hud/lobby/join_game.dmi
  icons/hud/lobby/lore.dmi
  icons/hud/lobby/migration.dmi
  icons/hud/lobby/ready.dmi
  sound/menu/attribution.txt
  sound/menu/button_press.ogg
  vanderlin.dme
Labels: Feature

#2682 Inhumen Cleric/Paladin
  code/__DEFINES/roguetown.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/modules/jobs/job_types/adventurer/types/_advclass.dm
  code/modules/jobs/job_types/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/adventurer/types/combat/clericinhumen.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/profanepaladin.dm
  vanderlin.dme
Labels: Feature, Fix, Removal

#2610 Apothecary QOL and some tweaks
  code/__DEFINES/ai/_ai.dm
  code/datums/ai/controllers/gnome.dm
  code/datums/components/pet_commands/gnome/tend_crops.dm
  code/modules/crafting/alchemy/essence_connector.dm
  code/modules/crafting/alchemy/infusion_recipes.dm
  code/modules/crafting/alchemy/precursors.dm
  code/modules/crafting/quality_of_crafting/alchemy.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/farming/soil.dm
Labels: Feature, Quality of Life

#2677 Anvil recipe PR
  code/_onclick/item_attack.dm
  code/controllers/subsystem/devotion.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/rotting.dm
  code/datums/components/twohanded.dm
  code/datums/locks/lock_access.dm
  code/datums/quality/_base_quality_manager.dm
  code/game/objects/items.dm
  code/game/objects/items/keys.dm
  code/game/objects/items/locks.dm
  code/game/objects/structures/pillory.dm
  code/game/rotational_objects/orphan_smasher.dm
  code/modules/clothing/belt/misc.dm
  code/modules/crafting/anvil_recipes/_anvil_recipe.dm
  code/modules/crafting/anvil_recipes/armor.dm
  code/modules/crafting/anvil_recipes/tools.dm
  code/modules/crafting/anvil_recipes/valuables.dm
  code/modules/crafting/anvil_recipes/weapons.dm
  code/modules/crafting/artificer/misc.dm
  code/modules/crafting/blueprinting/blueprints/carpentry.dm
  code/modules/crafting/quality_of_crafting/how_do_i_craft_this.dm
  code/modules/farming/structures/bin.dm
  code/modules/jobs/job_types/serfs/blacksmith.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
  icons/roguetown/misc/alchemy.dmi
  icons/roguetown/misc/forge.dmi
Labels: Balance

#2715 Fix Vampire Lord "A MONSTER" not appearing even not under a disguise
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#2695 Triumph Shop: UI improvements, 2 new triumph buys
  code/__DEFINES/roguetown.dm
  code/__HELPERS/round_statistics.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/storyteller.dm
  code/controllers/subsystem/triumph/buy_datums/character/pick_all_jobs_as_any_race.dm
  code/controllers/subsystem/triumph/buy_datums/character/pick_any_class.dm
  code/controllers/subsystem/triumph/buy_datums/communal/_communal.dm
  code/controllers/subsystem/triumph/buy_datums/communal/psydon_retirement_fund.dm
  code/controllers/subsystem/triumph/buy_datums/misc/psydon_favourite.dm
  code/controllers/subsystem/triumph/buy_datums/storyteller/bonus_influence.dm
  code/controllers/subsystem/triumph/buy_datums/triumph_buy_datums.dm
  code/controllers/subsystem/triumph/triumph_adjust_procs.dm
  code/controllers/subsystem/triumph/triumph_buy_menu.dm
  code/controllers/subsystem/triumph/triumphs.dm
  code/game/gamemodes/personal_objectives/abyssor/abyssoid_creation.dm
  code/game/gamemodes/personal_objectives/abyssor/fish_release.dm
  code/game/gamemodes/personal_objectives/abyssor/splash_water.dm
  code/game/gamemodes/personal_objectives/abyssor/take_bath.dm
  code/game/gamemodes/personal_objectives/astrata/become_noble.dm
  code/game/gamemodes/personal_objectives/astrata/recruit_retainer.dm
  code/game/gamemodes/personal_objectives/astrata/scorn_inhumen.dm
  code/game/gamemodes/personal_objectives/baotha/exploit_flaws.dm
  code/game/gamemodes/personal_objectives/baotha/sniff_drugs.dm
  code/game/gamemodes/personal_objectives/baotha/taste_lux.dm
  code/game/gamemodes/personal_objectives/dendor/butcher_animals.dm
  code/game/gamemodes/personal_objectives/dendor/make_wise_trees.dm
  code/game/gamemodes/personal_objectives/dendor/tame_animals.dm
  code/game/gamemodes/personal_objectives/eora/adopt_orphan.dm
  code/game/gamemodes/personal_objectives/eora/hug.dm
  code/game/gamemodes/personal_objectives/eora/matchmake.dm
  code/game/gamemodes/personal_objectives/graggar/eat_organs.dm
  code/game/gamemodes/personal_objectives/graggar/punch_targets.dm
  code/game/gamemodes/personal_objectives/graggar/splash_blood.dm
  code/game/gamemodes/personal_objectives/malum/craft_shrine.dm
  code/game/gamemodes/personal_objectives/malum/improve_craft.dm
  code/game/gamemodes/personal_objectives/malum/spend_energy.dm
  code/game/gamemodes/personal_objectives/matthios/hoard_mammons.dm
  code/game/gamemodes/personal_objectives/matthios/rob_graves.dm
  code/game/gamemodes/personal_objectives/matthios/theft.dm
  code/game/gamemodes/personal_objectives/necra/bury.dm
  code/game/gamemodes/personal_objectives/necra/embrace_death.dm
  code/game/gamemodes/personal_objectives/necra/hear_cries.dm
  code/game/gamemodes/personal_objectives/noc/baptism.dm
  code/game/gamemodes/personal_objectives/noc/get_apprentice.dm
  code/game/gamemodes/personal_objectives/noc/get_literate.dm
  code/game/gamemodes/personal_objectives/pestra/eat_rotten_food.dm
  code/game/gamemodes/personal_objectives/pestra/lux_extraction.dm
  code/game/gamemodes/personal_objectives/pestra/take_pain.dm
  code/game/gamemodes/personal_objectives/ravox/duel.dm
  code/game/gamemodes/personal_objectives/ravox/improve_combat.dm
  code/game/gamemodes/personal_objectives/ravox/ultimate_sacrifice.dm
  code/game/gamemodes/personal_objectives/xylix/coin_flip.dm
  code/game/gamemodes/personal_objectives/xylix/mock.dm
  code/game/gamemodes/personal_objectives/zizo/kick_man.dm
  code/game/gamemodes/personal_objectives/zizo/profane_shrines.dm
  code/game/gamemodes/personal_objectives/zizo/torture.dm
  code/modules/events/personal/necra/hear_cries.dm
  code/modules/spells/spell_types/pointed/ultimate_sacrifice.dm
  html/browser/slop_menustyle3.css
  vanderlin.dme
Labels: Feature, Quality of Life

#2505 Slight balance changes for bodypart wounds and crits
  code/modules/mob/living/living_wounds.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Test Merge, Balance, TEST MERGE ONLY

#2639 Minor Corsair tweak
  code/modules/jobs/job_types/other/merc_classes/corsair.dm
Labels: Balance

#2675 Fixes sword altgrip icons
  code/game/objects/items/weapons/melee/swords.dm
Labels: Fix

#2756 Quick Maniac Fixes
  code/modules/antagonists/villain/maniac/_maniac.dm
  code/modules/mob/living/carbon/rogfatstam.dm
Labels: Fix

#2762 Seek orphan fix
  code/modules/spells/spell_types/undirected/seek_orphan.dm
Labels: Code Maintenance

#2651 Triton Accent Change
  strings/accents/triton_replacement.json
Labels: Tweak

#2768 Increases how much influence Masterworks give to Malum
  code/datums/storytellers/gods.dm
Labels: Balance

#2789 sack fix
  code/modules/crafting/quality_of_crafting/natural_items.dm
Labels: Fix

#2744 Gives Hollow-kin Beastish-speak.
  code/modules/mob/living/carbon/human/species_types/demihumans/_demihuman.dm
Labels: Feature

#2783 Influences tweaks
  code/datums/storytellers/gods.dm
  code/modules/farming/soil.dm
  code/modules/farming/structures/wild_plant.dm
Labels: Tweak

#2752 General Mercenary Buffs
  code/modules/jobs/job_types/other/merc_classes/anthrax.dm
  code/modules/jobs/job_types/other/merc_classes/blackoak.dm
  code/modules/jobs/job_types/other/merc_classes/zalad.dm
Labels: Balance

#2670 Vanderlin forest shuffle
  _maps/map_files/vanderlin/vanderlin_forest.dmm
  code/modules/procedural_mapping/mapGeneratorModules/forest.dm
Labels: Test Merge, Mapping

#2717 Add a Gender Preference Option for a spouse
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/familytree.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/client/preferences/preferences_savefile.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Feature

#2803 Reverse changelog date entries too
  code/datums/changelog.dm
Labels: Fix, Logging

#2778 Triumph Buy DLC: Comedy and suffering
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/storyteller.dm
  code/controllers/subsystem/triumph/buy_datums/character/adoption.dm
  code/controllers/subsystem/triumph/buy_datums/character/fart.dm
  code/controllers/subsystem/triumph/buy_datums/character/leprosy.dm
  code/controllers/subsystem/triumph/buy_datums/character/pick_any_class.dm
  code/controllers/subsystem/triumph/buy_datums/communal/_communal.dm
  code/controllers/subsystem/triumph/buy_datums/communal/_preround.dm
  code/controllers/subsystem/triumph/buy_datums/communal/psydon_retirement_fund.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/stress.dm
  code/modules/mob/mob.dm
  vanderlin.dme
Labels: Feature

#2829 clothing no longer looks like shit
  code/modules/clothing/head/hood.dm
  code/modules/clothing/shirts/robe.dm
Labels: Fix

#2792 changes lock/unlock sound back to what it was before
  code/game/objects/objs.dm
  code/game/objects/structures/doors.dm
Labels: Test Merge, Sound

#2827 Offer and pointing qol
  code/__DEFINES/offer.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/datums/status_effects/debuffs.dm
  code/game/atom/atoms.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/effects/temporary_visuals/offered_item_effect.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/point.dm
  code/modules/mob/vision_cone.dm
  code/modules/unit_tests/unit_test.dm
  icons/effects/effects.dmi
  vanderlin.dme
Labels: Quality of Life

#2839 a few fixes
  code/datums/migrants/waves/jestertroupe.dm
  code/game/objects/items.dm
  code/game/objects/items/gear.dm
  code/modules/admin/admin.dm
  code/modules/events/personal/xylix/king_mockery.dm
  code/modules/events/personal/xylix/nobles_mockery.dm
  code/modules/farming/structures/bin.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/bard.dm
  code/modules/jobs/job_types/garrison/town_elder.dm
  code/modules/jobs/job_types/peasants/bard.dm
  code/modules/jobs/job_types/peasants/jester.dm
  code/modules/spells/spell_types/undirected/list_target/vicious_mockery.dm
Labels: Fix

#2818 Update of WPP and Rosewood
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/whitepalacepass/WhitePalacePass.dmm
Labels: Mapping

#2846 Xylix storyteller respects roundstart events
  code/datums/storytellers/_base.dm
  code/datums/storytellers/gods.dm
Labels: Feature

#2871 contextual actor
  code/modules/mapping/contextual_actor/contextual_actor.dm
  code/modules/mapping/contextual_actor/presets.dm
  icons/Testing/source.dmi
  vanderlin.dme
Labels: Mapping

#2804 Update damage procs
  code/modules/mob/living/carbon/damage_procs.dm
Labels: Fix

#2777 Itinerant and Dark Knight migrant changes
  code/datums/migrants/waves/dark_itinerant_knight_wave.dm
  code/datums/migrants/waves/itinerant_knight_wave.dm
Labels: Code Maintenance

#2771 Fix Antag's Patron getting removed while using adv classes
  code/modules/antagonists/villain/assassin.dm
  code/modules/events/antagonist/solo/minor/maniac.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/types/antag/roguemage.dm
  code/modules/jobs/job_types/adventurer/types/combat/dredge.dm
  code/modules/jobs/job_types/adventurer/types/combat/rare/swashbuckler.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/briar.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/rare/preacher.dm
  code/modules/jobs/job_types/church/adept.dm
  code/modules/jobs/job_types/garrison/town_elder.dm
  code/modules/mob/living/stats.dm
Labels: Fix, Test Merge, Removal

#2811 Necra Robe Sleeve Fix
  icons/roguetown/clothing/onmob/helpers/sleeves_armor.dmi
Labels: Fix, sprites

#2688 Makes Churn Undead Better Than Abrogation
  code/modules/spells/spell_types/pointed/aoe/churn_undead.dm
Labels: Balance

#2801 epic merchant PR
  code/datums/world_factions/coastal.dm
  code/datums/world_factions/mountain.dm
  code/datums/world_factions/zalad.dm
  code/game/objects/structures/fake_machines/merchant.dm
  code/modules/cargo/supply_packs/apparel.dm
  code/modules/cargo/supply_packs/armor.dm
  code/modules/cargo/supply_packs/drinks.dm
  code/modules/cargo/supply_packs/food.dm
  code/modules/cargo/supply_packs/jewelry.dm
  code/modules/cargo/supply_packs/luxury.dm
  code/modules/cargo/supply_packs/rawmat.dm
  code/modules/cargo/supply_packs/storage.dm
  code/modules/cargo/supply_packs/tools.dm
  code/modules/cargo/supply_packs/weapons.dm
  code/modules/clothing/gloves/leather.dm
  vanderlin.dme
Labels: Feature, Code Maintenance

#2936 Monarchs and priests
  code/__DEFINES/misc.dm
  code/__HELPERS/lordcolor.dm
  code/datums/heritage.dm
  code/modules/jobs/job_types/nobility/lord.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
Labels: Fix, Administration

#2823 Another Maniac Addition
  code/modules/antagonists/villain/maniac/_maniac.dm
  code/modules/events/antagonist/solo/minor/maniac.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature, Test Merge, Balance

#2880 Give zizo cult the cabal trait.
  code/modules/antagonists/villain/zizocult.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Code Maintenance

#2933 Moves woodcutter and footman ware axes to polearms file
  code/game/objects/items/weapons/melee/axes.dm
  code/game/objects/items/weapons/melee/polearms.dm
Labels: Code Maintenance

#2876 Roseewood & WPP APIARIES!
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/whitepalacepass/WhitePalacePass.dmm
Labels: Code Maintenance, Mapping

#2897 Refactor cleric holders a bit
  code/__DEFINES/faith.dm
  code/__DEFINES/traits.dm
  code/_globalvars/roguetown.dm
  code/controllers/subsystem/devotion.dm
  code/datums/faith/_devotion.dm
  code/datums/faith/devotion_subtypes.dm
  code/datums/gods/_patron.dm
  code/datums/gods/patrons/divine_pantheon.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/datums/migrants/waves/heartfell_wave.dm
  code/modules/admin/admin.dm
  code/modules/events/god_intervention/schism.dm
  code/modules/jobs/job_types/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/adventurer/types/combat/clericinhumen.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/paladin.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/profanepaladin.dm
  code/modules/jobs/job_types/adventurer/types/combat/monk.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/briar.dm
  code/modules/jobs/job_types/church/monk.dm
  code/modules/jobs/job_types/church/priest.dm
  code/modules/jobs/job_types/church/templar.dm
  code/modules/jobs/job_types/garrison/town_elder.dm
  code/modules/jobs/job_types/peasants/gravedigger.dm
  code/modules/jobs/job_types/youngfolk/churchling.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/spells/spell_types/pointed/healing.dm
  code/modules/spells/spell_types/pointed/inhumen_healing.dm
  code/modules/spells/spell_types/undirected/list_target/convert_role/church.dm
  vanderlin.dme
Labels: Code Maintenance

#2892 Death triumph loss changes
  code/modules/mob/living/carbon/human/death.dm
Labels: Feature

#2960 Triumph Buy DLC: Secret officiants and curses
  code/__DEFINES/roguetown.dm
  code/controllers/subsystem/triumph/buy_datums/challenges/curse.dm
  code/controllers/subsystem/triumph/buy_datums/challenges/leprosy.dm
  code/controllers/subsystem/triumph/buy_datums/character/officiant.dm
  code/controllers/subsystem/triumph/triumphs.dm
  code/datums/gods/patrons/curses.dm
  code/game/objects/items/coins.dm
  code/game/objects/items/weapons/rogueweapon.dm
  code/game/objects/structures/fake_machines/ATM.dm
  code/modules/spells/spell_types/pointed/ultimate_sacrifice.dm
  code/modules/surgery/surgeries/revival.dm
  vanderlin.dme
Labels: Feature

#2984 Printing press book fix
  code/controllers/subsystem/librarian.dm
  code/modules/library/lib_machines.dm
Labels: Fix

#2968 More tweaks
  _maps/map_files/debug/roguetest.dmm
  code/__DEFINES/map_exporter.dm
  code/__HELPERS/paths/mapping_helpers.dm
  code/controllers/subsystem/property_management.dm
  code/datums/liquids/liquid_effect.dm
  code/game/objects/fluff.dm
  code/game/objects/structures/doors.dm
  code/game/objects/structures/stairs.dm
  code/game/rotational_objects/fluid_objects/drain.dm
  code/game/turfs/closed/wall/walls.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/admin/verbs/map_export.dm
  icons/delver/abyss_objects.dmi
  icons/delver/abyss_walls.dmi
  icons/delver/desert_elevator.dmi
  icons/delver/desert_objects.dmi
  icons/delver/desert_sandstone.dmi
  icons/delver/desert_slopstone.dmi
  icons/delver/kelp.dmi
  vanderlin.dme
Labels: Code Maintenance, Mapping

#2861 Bottle labelling readded and better
  code/game/objects/items/waterskins.dm
  code/game/objects/items/weapons/ranged/flintlock.dm
  code/modules/farming/items/bottle_kit.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/bottles/_bottle.dm
  code/modules/reagents/reagent_containers/bottles/alchemy.dm
  code/modules/reagents/reagent_containers/bottles/beverages.dm
  icons/roguetown/items/glass_reagent_container.dmi
  vanderlin.dme
Labels: Feature

#2932 Cleric changes
  code/modules/jobs/job_types/adventurer/types/combat/cleric.dm
  code/modules/jobs/job_types/adventurer/types/combat/clericinhumen.dm
Labels: Test Merge

#2923 Vampire Fixes and Potence Change
  code/_onclick/item_attack.dm
  code/modules/antagonists/villain/neu_vampires/covens/coven_powers/potence.dm
  code/modules/antagonists/villain/neu_vampires/living_modifications.dm
  code/modules/antagonists/villain/vampire/objects/bloodpool.dm
  code/modules/antagonists/villain/vampire/objects/necrobook.dm
Labels: Fix, Test Merge, Balance, Code Maintenance, Quality of Life

#2945 Mentor Expansion
  code/modules/admin/mentor_stats.dm
  code/modules/admin/verbs/schizohelp.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  interface/interface.dm
  vanderlin.dme
Labels: Test Merge, Code Maintenance

#2914 Hammer time
  code/__DEFINES/weapons.dm
  code/game/objects/items/tools/hammer.dm
  code/game/objects/items/weapons/melee/blunt.dm
  code/modules/jobs/job_types/church/templar.dm
Labels: Feature, Code Maintenance

#2955 Soap changes
  code/datums/stress/positive_events.dm
  code/game/objects/items/soap.dm
Labels: Balance

#2750 (Minor) Forest Guard Rework!
  _maps/map_files/daftmarsh/map_adjustment_daftmarsh.dm
  _maps/map_files/rosewood/map_adjustment_rosewood.dm
  _maps/map_files/whitepalacepass/map_adjustment_whitepalacepass.dm
  code/datums/map_adjustment.dm
  code/modules/clothing/armor/forestguardarmor.dm
  code/modules/clothing/belt/misc.dm
  code/modules/jobs/job_types/garrison/forestguard.dm
  code/modules/jobs/job_types/garrison/forestwarden.dm
  code/modules/mob/living/carbon/human/voicepacks/genfemale.dm
  code/modules/mob/living/carbon/human/voicepacks/genmale.dm
  code/modules/mob/living/emote.dm
  sound/vo/female/gen/haltyellorphan (1).ogg
  sound/vo/female/gen/haltyellorphan (2).ogg
  sound/vo/male/gen/haltyellorphan (1).ogg
  sound/vo/male/gen/haltyellorphan (2).ogg
Labels: Feature, Balance, Code Maintenance, Mapping

#2910 Blessed needle can repair clothes
  code/game/objects/items/needle.dm
Labels: Test Merge, Balance

#2954 Flight QOL and eating worms
  code/datums/components/abberant_eater.dm
  code/modules/mob/living/carbon/human/species_types/harpy/_harpy.dm
  code/modules/surgery/organs/external/wings/functional_wings.dm
Labels: Feature, Test Merge, Code Maintenance, Quality of Life

#3004 Lock unlock animations
  _maps/map_files/debug/roguetest.dmm
  code/datums/locks/_lock.dm
  code/datums/locks/lock_access.dm
Labels: Quality of Life, Mapping

#3037 Churchling status gets first miracle
  code/datums/faith/_devotion.dm
  code/datums/faith/devotion_subtypes.dm
Labels: Fix

#3015 Fixes #2986 and a bit more
  code/modules/crafting/alchemy/essence_machines/essence_nodes.dm
  code/modules/crafting/alchemy/essence_machines/node_harvester.dm
  code/modules/crafting/alchemy/essence_machines/node_jar.dm
Labels: Fix

#2931 Towner Skill Slop
  code/modules/jobs/job_types/church/monk.dm
  code/modules/jobs/job_types/church/templar.dm
  code/modules/jobs/job_types/nobility/courtphys.dm
  code/modules/jobs/job_types/nobility/feldsher.dm
  code/modules/jobs/job_types/nobility/magician.dm
  code/modules/jobs/job_types/nobility/nightman.dm
  code/modules/jobs/job_types/peasants/hunter.dm
  code/modules/jobs/job_types/peasants/miner.dm
  code/modules/jobs/job_types/serfs/artificer.dm
  code/modules/jobs/job_types/serfs/innkeep.dm
Labels: Balance

#2964 Psydon Paladin Change and Fixes
  code/__DEFINES/roguetown.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/paladin.dm
  code/modules/spells/spell_types/undirected/list_target/convert_role/church.dm
Labels: Fix, Balance

#3045 Minor Artificier (and blacksmith) recipe changes
  code/modules/crafting/anvil_recipes/weapons.dm
  code/modules/crafting/artificer/misc.dm
Labels: Feature

#2905 Encumbrance changes. Plate armor nerfs pt 1
  code/modules/clothing/armor/misc.dm
  code/modules/clothing/armor/plate.dm
  code/modules/clothing/armor/rare.dm
  code/modules/clothing/armor/steam.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_movement.dm
Labels: Balance

#3072 Fixes Good Swim Trait name
  code/__DEFINES/traits.dm
Labels: Fix

#2997 Bumping with Keys Unlocks Doors
  code/game/objects/structures/doors.dm
Labels: Feature, Test Merge

#2930 Weapon defines and stuff
  code/__DEFINES/weapons.dm
  code/game/objects/items/tools/farmtools.dm
  code/game/objects/items/tools/gravetools.dm
  code/game/objects/items/weapons/melee/axes.dm
  code/game/objects/items/weapons/melee/blunt.dm
  code/game/objects/items/weapons/melee/flail.dm
  code/game/objects/items/weapons/melee/knives.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/game/objects/items/weapons/scabbard.dm
  code/game/objects/structures/fake_machines/mail.dm
  code/modules/farming/items/tools.dm
  code/modules/jobs/job_types/church/adept.dm
  tools/UpdatePaths/Scripts/2930_weapon_defines_and_stuff.txt
Labels: Code Maintenance

#3055 Culinary Preferences
  code/__DEFINES/food.dm
  code/datums/stress/foods.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/client/preferences/preferences_culinary.dm
  code/modules/client/preferences/preferences_savefile.dm
  code/modules/cooking/raw/NeuFood_dough.dm
  code/modules/cooking/raw/NeuFood_meat.dm
  code/modules/cooking/raw/NeuFood_processed.dm
  code/modules/cooking/raw/NeuFood_veggies.dm
  code/modules/farming/items/produce/_produce.dm
  code/modules/fishing/fish.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/reagents/chemistry/reagents/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/food_reagents.dm
  code/modules/surgery/organs/_organ.dm
  vanderlin.dme
Labels: Feature

#3069 Multi-line Emotes
  code/__DEFINES/say.dm
  code/controllers/subsystem/input.dm
  code/modules/mob/mob_say.dm
  code/modules/mob/typing_indicator.dm
Labels: Feature

#3087 Fix status effect process overrides
  code/datums/status_effects/status_effect.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/summons/void/void_dragon.dm
  code/modules/spells/spell_types/pointed/aoe/abrogation.dm
Labels: Fix

#3070 Mute Ambience Music
  code/controllers/subsystem/ambience.dm
  code/modules/admin/verbs/playsound.dm
Labels: Sound

#3071 Removes Void Corruption from Red Dragon and it's subtypes.
  code/modules/mob/living/simple_animal/hostile/retaliate/red_dragon.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/summons/void/void_dragon.dm
Labels: Removal

#3060 Replaces "oz" with "ligulae"
  code/__HELPERS/reagents.dm
  code/datums/brewing_recipes/_base.dm
  code/datums/components/container_craft/recipes/_base.dm
  code/datums/components/container_craft/recipes/cooking_pot/_cooking_pot.dm
  code/datums/liquids/liquid_effect.dm
  code/game/atom/atoms.dm
  code/game/objects/items/crucible.dm
  code/game/objects/items/pouring_mould.dm
  code/modules/crafting/alchemy/cauldron_recipes.dm
  code/modules/farming/structures/fermentation_keg.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/visual_ui/recipe_booklet/elements/recipe_display.dm
Labels: Quality of Life

#3048 Cleanup food vars
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/rosewood/rosewood_marsh.dmm
  _maps/map_files/shared/CentCom.dmm
  _maps/map_files/vanderlin/vanderlin_forest.dmm
  _maps/matthios_tomb/room/SteamCastle.dmm
  code/game/objects/items/storage/cook_kit.dm
  code/modules/client/preferences/preferences_culinary.dm
  code/modules/cooking/NeuFood.dm
  code/modules/cooking/cooked/NeuFood_snacks.dm
  code/modules/cooking/raw/NeuFood_dough.dm
  code/modules/crafting/quality_of_crafting/cooking/biscuits.dm
  code/modules/fishing/fish.dm
  code/modules/food_and_drinks/food/snacks.dm
  code/modules/mob/living/simple_animal/hostile/smallrat.dm
Labels: Code Maintenance, Mapping
