Repository Monkestation/Vanderlin, pull requests merged in 2025-07, with the labels that each got.

#2339 OD lints: ignore unsupported and error on ambiguous order
  tools/ci/od_lints.dm
Labels: Tooling

#2272 Better mentoring
  code/__DEFINES/chat/div.dm
  code/__DEFINES/chat/span.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/traits.dm
  code/_globalvars/traits.dm
  code/controllers/subsystem/timer.dm
  code/modules/admin/verbs/schizohelp.dm
  code/modules/client/preferences/preferences_savefile.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/living/emote.dm
  vanderlin.dme
Labels: Fix, Tweak

#2337 Map table remake.
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/structures/tables_racks.dm
  code/modules/clothing/neck/psycross.dm
  code/modules/mob/living/carbon/human/species_types/rakshari/_rakshari.dm
  icons/roguetown/misc/tables.dmi
  strings/accents/accent_universal.json
Labels: Mapping

#2363 Restore asset.md for attribution and remove a non-free use sprite
  assets.md
  code/modules/crafting/alchemy/essence_machines/research_matrix/research_matrix.dm
  icons/roguetown/misc/splitter.dmi
Labels: Removal

#2353 Mercator's Eye
  _maps/map_files/shared/CentCom.dmm
  code/modules/clothing/neck/misc.dm
  code/modules/jobs/job_types/nobility/merchant.dm
Labels: Mapping

#2269 Sound cache for ambience (RUSTG) + kill SSdroning in favour of SEND_SOUND and channels
  .github/workflows/ci_suite.yml
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/rust_g.dm
  code/__DEFINES/sound.dm
  code/__HELPERS/roundend.dm
  code/_globalvars/lists/ambience.dm
  code/controllers/subsystem/ambience.dm
  code/controllers/subsystem/music_update.dm
  code/controllers/subsystem/nightshift.dm
  code/controllers/subsystem/sounds.dm
  code/datums/status_effects/debuffs.dm
  code/game/area/areas.dm
  code/game/area/areas/centcom.dm
  code/game/area/areas/dungeon.dm
  code/game/area/areas/tomb.dm
  code/game/area/roguetownareas.dm
  code/game/area/vanderlin/vanderlinareas.dm
  code/modules/admin/verbs/playsound.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/villain/harlequinn/enhanced_mimicry.dm
  code/modules/antagonists/villain/maniac/_maniac.dm
  code/modules/antagonists/villain/vampire/objects/scrying.dm
  code/modules/antagonists/villain/werewolf/werewolf_transformation.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/droning/droning.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/spirit/spirit.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/reagent_containers/powder.dm
  code/modules/spells/spell_types/invoked/acolyte/noc.dm
  code/modules/spells/spell_types/wizard/utility/mimicry.dm
  code/modules/spells/spell_types/wizard/utility/shadow_step.dm
  code/modules/underworld/underworld.dm
  dependencies.sh
  sound/misc/area.ogg
  sound/misc/stings/generic.ogg
  vanderlin.dme
Labels: Github

#2377 [Bounty][Port] Pronouns/body selector; OOC Pronouns
  code/__DEFINES/chat/span.dm
  code/__DEFINES/preferences.dm
  code/__DEFINES/role_bans.dm
  code/__HELPERS/pronouns.dm
  code/__HELPERS/text.dm
  code/datums/emotes.dm
  code/datums/tgs_handler.dm
  code/modules/client/preferences/_preferences.dm
  code/modules/client/preferences/preferences_savefile.dm
  code/modules/client/verbs/ooc.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/mob/dead/new_player/preferences_setup.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/demihumans/_demihuman.dm
  code/modules/mob/living/carbon/human/species_types/kobold/_kobold.dm
  code/modules/mob/living/carbon/human/species_types/other/halforc.dm
  code/modules/mob/living/carbon/human/species_types/triton/_triton.dm
  code/modules/mob/living/living_descriptors.dm
  code/modules/mob/mob_defines.dm
Labels: Test Merge

#2412 Fix casting on non valid targets and missed parent calls
  _maps/map_files/rosewood/rosewood_marsh.dmm
  _maps/matthios_tomb/hallway/Malphpiece3.dmm
  code/_onclick/drag_drop.dm
  code/_onclick/item_attack.dm
  code/game/objects/structures/fluff.dm
  code/game/turfs/open/water.dm
  code/modules/spells/spell.dm
  code/modules/spells/spell_types/pointed/blindness.dm
  code/modules/spells/spell_types/pointed/status/_status.dm
Labels: Mapping

#2386 Bump byond version for tests
  .github/actions/restore_or_install_byond/action.yml
  .github/workflows/ci_suite.yml
  dependencies.sh
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Github

#2419 Fix merc guild oven.
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#2424 Examining uses gender unless you know the person
  code/__HELPERS/pronouns.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Test Merge

#2427 Ports Azure Peaks Knight Armet and gives it to the Royal Knights
  code/modules/clothing/head/helmets/misc.dm
  code/modules/jobs/job_types/garrison/royal_knight.dm
  icons/roguetown/clothing/head.dmi
  icons/roguetown/clothing/onmob/head.dmi
Labels: Bounty, Port

#2464 Restore troll horn sprite
  icons/roguetown/misc/alchemy.dmi
Labels: sprites

#2452 Holy hand grenade
  code/game/objects/items/bombs.dm
  icons/obj/bombs.dmi
  icons/obj/holy_grenade.dmi
  icons/roguetown/items/cooking.dmi
  icons/roguetown/items/misc.dmi
Labels: Bounty

#2478 Cache key for rust g
  .github/workflows/ci_suite.yml
Labels: Github

#2481 Vanderlin v5; The Steampunkification of the City of Vanderlin (Part 1)
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_bog.dmm
  code/game/area/roguetownareas.dm
  code/game/objects/herbs.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/items/mageitems.dm
  code/game/objects/items/perfume.dm
  code/game/objects/lighting/_base_roguestreet.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/beds_chairs/sofa.dm
  code/game/objects/structures/carpets.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/walldeco.dm
  code/game/turfs/closed/wall/walls.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/modules/crafting/alchemy/essence_machines/research_matrix/research_matrix.dm
  code/modules/crafting/quality_of_crafting/natural_items.dm
  code/modules/reagents/reagent_containers/bucket/pot.dm
  icons/obj/dice.dmi
  icons/roguetown/items/chairs.dmi
  icons/roguetown/items/cooking.dmi
  icons/roguetown/items/glass_reagent_container.dmi
  icons/roguetown/items/perfume.dmi
  icons/roguetown/misc/96x96.dmi
  icons/roguetown/misc/alchemy.dmi
  icons/roguetown/misc/couch.dmi
  icons/roguetown/misc/decoration.dmi
  icons/roguetown/misc/herbfoliage.dmi
  icons/roguetown/misc/lighting.dmi
  icons/roguetown/misc/pipes.dmi
  icons/roguetown/misc/rituals.dmi
  icons/roguetown/misc/structure.dmi
  icons/roguetown/misc/tree.dmi
  icons/turf/areas.dmi
  icons/turf/areas_manor.dmi
  icons/turf/floors.dmi
  icons/turf/window.dmi
Labels: Mapping

#2411 adds entry requirements to portals / town dungeon only enter or exit during day
  _maps/map_files/shared/dungeon.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/datums/dungeon_generator/dungeon_entry_exit.dm
Labels: Mapping, FROZEN, Bounty

#2545 Fixes Apartment 11 having the wrong key
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#2581 Fix windows to test changelog
  code/game/objects/structures/window.dm
Labels: Fix

#2590 essence spells fix
  code/modules/crafting/alchemy/essence_machines/essence_gauntlet/spells.dm
Labels: Fix
