Repository Monkestation/Vanderlin, pull requests merged in 2025-10, with the labels that each got.

#3366 Migrant Waves now gets their greeting text at the migrant menu.
  code/datums/migrants/migrant_pref.dm
Labels: Code Maintenance

#3441 Give coin to the vampire lord
  code/modules/antagonists/villain/vampire/lord.dm
Labels: Feature

#3520 Coronate Verb at the VV Dropdown
  code/__DEFINES/vv.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Administration

#3507 Server status config update
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  config/config.txt
Labels: Config

#3439 make silver enchantment only proc from weapons
  code/datums/enchantments/silver.dm
Labels: Code Maintenance

#3542 Expands Rejected Royal's allowed species
  code/modules/jobs/job_types/adventurer/types/wretch/reject.dm
Labels: Feature

#3298 Remove Age modifier for Maniac/Lich and Trey Liam change
  code/modules/antagonists/villain/lich/lich.dm
  code/modules/antagonists/villain/maniac/_maniac.dm
Labels: Balance, Removal

#3320 Wretch Changes
  code/game/objects/items/bombs.dm
  code/game/objects/items/explosives/poison_bomb.dm
  code/modules/antagonists/roleobjs/wretch.dm
  code/modules/crafting/quality_of_crafting/bombs.dm
  code/modules/jobs/job_types/adventurer/types/wretch/bloodsucker.dm
  code/modules/jobs/job_types/adventurer/types/wretch/deserter.dm
  code/modules/jobs/job_types/adventurer/types/wretch/reject.dm
  code/modules/jobs/job_types/adventurer/wretch.dm
  code/modules/spells/spell_types/pointed/conjure/rous.dm
  code/modules/spells/spell_types/undirected/conjure_item/poison_bomb.dm
  code/modules/spells/spell_types/undirected/conjure_item/puffer.dm
  vanderlin.dme
Labels: Feature, Balance

#3301 Hedge Mage nerfs.dm
  code/modules/jobs/job_types/adventurer/types/wretch/hedgemage.dm
Labels: Balance

#3452 The Peddlering pt. 2
  code/game/objects/structures/fake_machines/vendor.dm
  icons/roguetown/misc/machines.dmi
Labels: Feature, Fix, Town, Services

#3500 Make restricted roles less strict for antagonists rolls that create a new person.
  code/modules/events/antagonist/solo/lich.dm
  code/modules/events/antagonist/solo/vampires.dm
Labels: Code Maintenance

#3599 Makes alchemy spells use alchemy as the associated skill
  code/modules/crafting/alchemy/essence_machines/essence_gauntlet/spells/_base.dm
Labels: Fix

#3615 Fix advclass names
  code/controllers/subsystem/role_class_handler/role_class_handler.dm
  code/modules/jobs/job_types/_job.dm
Labels: Fix

#3617 fix bloodsucker
  code/modules/antagonists/villain/vampire/_vampire.dm
  code/modules/jobs/job_types/adventurer/types/wretch/bloodsucker.dm
Labels: Fix

#3595 Makes Instruments craftable
  code/modules/crafting/quality_of_crafting/crafting.dm
Labels: Feature

#3624 Fix consort, court agent and prisoner being unplayable roundstart.
  code/controllers/subsystem/job.dm
Labels: Fix

#3646 Fixes Migrants not being foreigners
  code/datums/migrants/migrant_job.dm
  code/datums/migrants/waves/prisoner_wave.dm
Labels: Fix

#3647 Fixes ALL adv classes using their parent job name
  code/modules/jobs/job_types/adventurer/types/_advclass.dm
  code/modules/jobs/job_types/garrison/gatemaster.dm
  code/modules/jobs/job_types/garrison/royal_knight.dm
  code/modules/jobs/job_types/garrison/veteran.dm
Labels: Fix

#3423 Changes craftdiff requirement for noose structure to a delay.
  code/modules/crafting/blueprinting/blueprints/carpentry.dm
Labels: Feature, Fix

#3607 Change How Continue Vote works and Remove Old First vote code
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/triumph/buy_datums/communal/longer_week.dm
  code/controllers/subsystem/vote.dm
Labels: Feature

#3611 Add "control undead" spell to game
  code/modules/jobs/job_types/adventurer/types/wretch/necromancer.dm
  code/modules/spells/spell_types/pointed/control_undead.dm
  vanderlin.dme
Labels: Feature

#3490 Palace changes
  _maps/map_files/whitepalacepass/WhitePalacePass.dmm
  _maps/map_files/whitepalacepass/map_adjustment_whitepalacepass.dm
  config/maps.txt
Labels: Code Maintenance, Mapping

#3665 Fixes meat handpie using the wrong mince type
  code/modules/crafting/quality_of_crafting/cooking/raw_handpies.dm
Labels: Fix

#3660 Remove stickybans
  SQL/database_changelog.txt
  SQL/tgstation_schema.sql
  SQL/tgstation_schema_prefixed.sql
  SQL/tgstation_schema_prefixed1.sql
  code/__DEFINES/admin.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/lists/admin.dm
  code/controllers/subsystem/stickyban.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/client/client_procs.dm
  vanderlin.dme
Labels: Removal, SQL

#3663 Fix spell "control_undead" and add it to lich
  code/modules/antagonists/villain/lich/lich.dm
  code/modules/spells/spell_types/pointed/control_undead.dm
Labels: Feature, Fix, Removal

#3671 child/dwarf sprites for templar tabards + robe slot change
  code/modules/clothing/shirts/robe.dm
  icons/roguetown/clothing/special/onmob/templar.dmi
Labels: Tweak, Sprites
