Repository Monkestation/Vanderlin, pull requests merged in 2025-05, with the labels that each got.

#1719 Resprites dwarves.
  icons/roguetown/mob/bodies/f/fd.dmi
  icons/roguetown/mob/bodies/f/fm.dmi
  icons/roguetown/mob/bodies/m/md.dmi
Labels: Feature, sprites

#1643 Remove roguetown.dmm and related maps
  _maps/map_files/roguetown.dm
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/roguetown/smalldecap.dmm
  _maps/map_files/roguetown/smallforest.dmm
  _maps/map_files/roguetown/smallforest.json
  _maps/map_files/roguetown/smallswamp.dmm
  _maps/map_files/roguetown/smallswamp.json
  _maps/roguetown.json
  config/maps.txt
Labels: Mapping, removal

#1708 Drow Knight and Squire sexism update
  code/datums/migrants/waves/dark_itinerant_knight_wave.dm
Labels: Tweak

#1720 Removes Last Class restriction from a few roles.
  code/modules/jobs/job_types/church/templar.dm
  code/modules/jobs/job_types/peasants/hunter.dm
  code/modules/jobs/job_types/peasants/miner.dm
  code/modules/jobs/job_types/serfs/carpenter.dm
Labels: removal

#1740 fixes spell logs runtime
  code/modules/spells/spell.dm
Labels: Logging

#1728 removes bladesinger
  code/modules/jobs/job_types/adventurer/types/combat/donator/bladesinger.dm
  vanderlin.dme
Labels: removal

#1569 Map switch again but without cbt
  .vscode/launch.json
  .vscode/tasks.json
  code/__DEFINES/map_switch.dm
  code/datums/particle_weathers/datum_types/snow_storm.dm
  code/game/objects/effects/decals/cleanable/humans.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/structures/mage_structures.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/turfs/open/floor/roguefloor.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/water.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/poltergeist.dm
  icons/roguetown/misc/doors.dmi
  icons/turf/floors.dmi
  vanderlin.dme
Labels: Code Maintenance, Mapping, DO NOT MERGE, FUCK

#1700 Vanderlin Train Station Rework
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/structures/train.dm
  icons/roguetown/items/train.dmi
Labels: Mapping

#1745 Removes Feldsher Nobility
  code/modules/jobs/job_types/nobility/feldsher.dm
Labels: removal

#1674 Aasimar skin tone update
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species_types/other/aasimar.dm
Labels: Tweak

#1768 Forest Brawler becomes Forest Reaver
  code/modules/jobs/job_types/garrison/forestguard.dm
  code/modules/jobs/job_types/garrison/forestwarden.dm
Labels: Test Merge, Balance

#1793 Fix daftmarsh mortars
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
Labels: Mapping

#1697 Aasimar hunger debuff removed and added to half-orcs
  code/modules/mob/living/carbon/human/species_types/other/aasimar.dm
  code/modules/mob/living/carbon/human/species_types/other/halforc.dm
Labels: removal, 👎 DISAPPROVED

#1683 Inhumen Lair now becomes Lich Spawning Grounds
  _maps/map_files/debug/roguetest.dmm
  _maps/map_files/shared/CentCom.dmm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/game/area/roguetownareas.dm
  code/game/objects/items/candle.dm
  code/game/objects/lighting/rogue_fires.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/rogueflora.dm
  icons/roguetown/items/lighting.dmi
  icons/roguetown/misc/64x128.dmi
  icons/roguetown/misc/96x96.dmi
  icons/roguetown/misc/decoration.dmi
  icons/roguetown/misc/foliage.dmi
  icons/roguetown/misc/foliagetall.dmi
  icons/roguetown/misc/lighting.dmi
  icons/roguetown/misc/structure.dmi
  icons/roguetown/misc/tables.dmi
  icons/roguetown/misc/tallstructure.dmi
Labels: Test Merge, Mapping

#1800 Fix winch in lich place
  _maps/map_files/shared/CentCom.dmm
Labels: Mapping

#1750 spell casting log improevemnets
  code/modules/spells/spell.dm
Labels: Logging

#1809 Attack animations
  code/__DEFINES/combat.dm
  code/__DEFINES/qdel.dm
  code/__HELPERS/game.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/datums/stock/bounties.dm
  code/game/atom/atoms_movable.dm
  code/game/machinery/artificer_table.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/intents.dm
  code/game/objects/obj_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
Labels: Test Merge

#1818 Remove immortal from Hollowkin
  code/modules/mob/living/carbon/human/species_types/demihumans/_demihuman.dm
Labels: removal

#1820 fix heirs runtime
  code/datums/heritage.dm
Labels: Fix

#1828 improvements for admin logging
  code/modules/admin/topic.dm
Labels: Logging

#1810 byond native context menu is always active for admins but rebinded to CTRL+RMB
  code/datums/keybinding/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client_procs.dm
  code/modules/keybindings/bindings_carbon.dm
  code/modules/mob/login.dm
  interface/skin.dmf
  vanderlin.dme
Labels: Test Merge

#1590 Triumph Unbuy refunds 100%
  code/controllers/subsystem/triumph/triumphs.dm
Labels: Balance

#1785 Mage Attunement Changes
  code/datums/mana/attunement.dm
Labels: Balance

#1819 Continued runtime fixes
  code/__DEFINES/dcs/signals/signals_mob/signals_living.dm
  code/_onclick/hud/alert.dm
  code/datums/ai/controllers/zombie.dm
  code/datums/chatmessage.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/hidden_doors.dm
  code/game/objects/structures/train.dm
  code/modules/antagonists/villain/vampire/objects/portal.dm
  code/modules/mob/living/carbon/human/species_types/other/werewolf.dm
  code/modules/mob/living/living.dm
  code/modules/underworld/underworld.dm
Labels: Test Merge, Code Maintenance

#1817 Food preservation
  code/game/turfs/open/_open.dm
  code/modules/food_and_drinks/food/snacks.dm
Labels: Test Merge

#1812 Royal Knight buff and Steam Knight seperation
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/modules/clothing/armor/steam.dm
  code/modules/clothing/cloak/steam.dm
  code/modules/clothing/gloves/steam.dm
  code/modules/clothing/head/helmets/steam.dm
  code/modules/clothing/shoes/steam.dm
  code/modules/jobs/job_types/garrison/royal_knight.dm
  code/modules/jobs/job_types/garrison/royalguard.dm
  code/modules/jobs/job_types/peasants/bard.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/mob.dm
  vanderlin.dme
Labels: Test Merge, Balance, Mapping, TEST MERGE ONLY

#1704 [Bug fix] Spangenhelm worn sprite 2
  code/modules/clothing/head/helmets/heavy.dm
Labels: DO NOT MERGE

#1710 Fog clearing done again
  code/datums/components/movable_lighting.dm
  code/datums/particle_weathers/datum_types/fog.dm
  code/game/objects/lighting/_base_light.dm
  code/game/objects/lighting/_base_roguelight.dm
  code/game/objects/lighting/_base_roguestreet.dm
  code/game/objects/lighting/lantern_post.dm
  code/game/objects/lighting/rogue_fires.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/living/living.dm
  icons/effects/light_overlays/light_128.dmi
  icons/effects/light_overlays/light_160.dmi
  icons/effects/light_overlays/light_192.dmi
  icons/effects/light_overlays/light_224.dmi
  icons/effects/light_overlays/light_256.dmi
  icons/effects/light_overlays/light_288.dmi
  icons/effects/light_overlays/light_32.dmi
  icons/effects/light_overlays/light_320.dmi
  icons/effects/light_overlays/light_352.dmi
  icons/effects/light_overlays/light_64.dmi
  icons/effects/light_overlays/light_96.dmi
Labels: Test Merge, Tweak

#1840 Adds changes to rosewood that was supposed to be present in the court physician update
  _maps/map_files/rosewood/rosewood.dmm
Labels: Mapping

#1850 Immigration/exit config based on map
  _maps/daftmarsh.json
  _maps/roguetest.json
  _maps/rosewood.json
  _maps/vanderlin.json
  code/datums/map_config.dm
  code/game/objects/structures/train.dm
  code/modules/jobs/job_types/_job.dm
Labels: Mapping

#1847 rosewood fixes
  _maps/map_files/rosewood/rosewood.dmm
Labels: Mapping

#1813 Removes Alchemical Potions from Goldface
  code/modules/cargo/supply_packs/drinks.dm
Labels: Removal

#1837 Vampire armours fix and clean
  code/modules/antagonists/villain/vampire/objects/bloodpool.dm
  code/modules/clothing/armor/chainmail.dm
  code/modules/clothing/armor/misc.dm
  code/modules/clothing/gloves/chain.dm
  code/modules/clothing/head/helmets/heavy.dm
  code/modules/clothing/pants/plate_legs.dm
  code/modules/clothing/shoes/boots.dm
Labels: Fix

#1786 All zizo worshippers can draw and use zizo cult runes/rituals
  code/datums/gods/_patron.dm
  code/datums/gods/patrons/curses.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/modules/antagonists/villain/zizocult.dm
Labels: DO NOT MERGE

#1863 Fix daftmarsh lava big mistake
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
Labels: Mapping

#1841 More runtime fixes
  code/controllers/subsystem/plexora.dm
  code/datums/wounds/fractures.dm
  code/game/objects/structures/doors.dm
  code/modules/mob/living/carbon/human/npc/skeleton.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/summons/infernal/hellhound.dm
  code/modules/mob/login.dm
  code/modules/surgery/surgeries/plastic_surgery.dm
Labels: Fix

#1814 Captain nerf
  code/modules/jobs/job_types/nobility/captain.dm
Labels: Balance

#1774 Mercenary balance adjustments
  code/modules/jobs/job_types/garrison/garrisonguard.dm
  code/modules/jobs/job_types/other/merc_classes/anthrax.dm
  code/modules/jobs/job_types/other/merc_classes/blackoak.dm
  code/modules/jobs/job_types/other/merc_classes/boltslinger.dm
  code/modules/jobs/job_types/other/merc_classes/corsair.dm
  code/modules/jobs/job_types/other/merc_classes/grenzelhoft.dm
  code/modules/jobs/job_types/other/merc_classes/steppesman.dm
  code/modules/jobs/job_types/other/merc_classes/underdweller.dm
Labels: Balance

#1871 Daftmarsh patching + locked steward closet.
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/structures/crates_lockers/crafted_closet.dm
  code/game/objects/structures/train.dm
  icons/roguetown/underworld/enigma_carriage.dmi
Labels: Mapping

#1851 Decorstone wall smoothening for Vandelrin and Rosewood.
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping, hell yes

#1866 Map-based monarch titles.
  _maps/daftmarsh.json
  _maps/roguetest.json
  _maps/rosewood.json
  _maps/vanderlin.json
  code/datums/map_config.dm
  code/modules/jobs/job_types/nobility/lord.dm
Labels: Mapping

#1862 Update map adjustments
  _maps/map_files/daftmarsh/map_adjustment_daftmarsh.dm
  _maps/map_files/rosewood/map_adjustment_rosewood.dm
  code/controllers/subsystem/mapping.dm
  code/datums/map_adjustment.dm
Labels: Mapping

#1881 Rosewood Fixes/Updates
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/rosewood/rosewood_forest.dmm
Labels: Mapping

#1880 Adds an addition travel point to the bog to the Forest and Mountain for Vanderlin
  _maps/map_files/vanderlin/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin_forest.dmm
  _maps/map_files/vanderlin/vanderlin_mountain.dmm
Labels: Mapping

#1767 Wrestling changes
  code/__DEFINES/combat.dm
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/other_mobs.dm
  code/datums/keybinding/mob.dm
  code/game/atom/atoms_movable.dm
  code/game/objects/items/melee/transforming.dm
  code/game/objects/structures/newtree.dm
  code/game/objects/structures/stairs.dm
  code/game/turfs/closed/_closed.dm
  code/game/turfs/open/openspace.dm
  code/modules/jobs/job_types/adventurer/types/antag/brigand.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/npc/skeleton.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/grabbing.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
  code/modules/surgery/bodyparts/_bodyparts.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  icons/mob/screen_gen.dmi
  sound/combat/grabbreak.ogg
  sound/combat/grabstruggle.ogg
Labels: Test Merge, Balance

#1775 [Port] Multi-z movement touchups
  code/__HELPERS/AStar.dm
  code/datums/ai/ai_movement/astar_movement.dm
  code/datums/ai/ai_movement/hybrid_movement.dm
  code/datums/components/leash.dm
  code/datums/dungeon_generator/dungeon_entry_exit.dm
  code/datums/rotational_speed_data.dm
  code/datums/rts/building_datums/_base_datum.dm
  code/datums/rts/controller_mob.dm
  code/datums/rts/work_mind.dm
  code/datums/rts/work_orders/_base_task.dm
  code/datums/rts/work_orders/orders/haul_materials.dm
  code/datums/rts/work_orders/orders/store_materials.dm
  code/game/atom/atoms_movable.dm
  code/game/objects/structures/doors.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/stairs.dm
  code/game/objects/structures/traveltile.dm
  code/game/objects/structures/well.dm
  code/game/turfs/open/lava.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/open/water.dm
  code/game/turfs/turf.dm
  code/modules/client/customizer/customizers/organ/wings.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/carbon/spirit/combat.dm
  code/modules/mob/living/living_movement.dm
Labels: Test Merge, Mapping

#1842 Heart crit requires rib fracture first or specific bclass
  code/__DEFINES/combat.dm
  code/_globalvars/lists/wounds.dm
  code/datums/wounds/arteries.dm
  code/game/objects/items/weapons/ranged/ammo.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Balance, Tweak

#1907 Unique Templar Weapons
  code/__DEFINES/roguetown.dm
  code/game/objects/items/weapons/melee/axes.dm
  code/game/objects/items/weapons/melee/blunt.dm
  code/game/objects/items/weapons/melee/flail.dm
  code/game/objects/items/weapons/melee/knives.dm
  code/game/objects/items/weapons/melee/polearms.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/game/objects/items/weapons/melee/whips.dm
  code/modules/jobs/job_types/church/templar.dm
  code/modules/spells/spell_types/invoked/acolyte/malum.dm
  icons/roguetown/weapons/32.dmi
  icons/roguetown/weapons/64.dmi
Labels: Test Merge

#1936 Revert "removes bladesinger" and nerf it abit
  code/modules/jobs/job_types/adventurer/types/combat/donator/bladesinger.dm
  vanderlin.dme
Labels: Removal

#1952 Fixes Aasimar swordmaster spawning without their armor, remove dwarf from being aple to play sword master(no armor sprite for them)
  code/modules/clothing/armor/rare.dm
  code/modules/clothing/gloves/rare.dm
  code/modules/clothing/head/rare.dm
  code/modules/clothing/shoes/rare.dm
  code/modules/jobs/job_types/adventurer/types/combat/donator/swordmaster.dm
Labels: Removal

#1970 Antagonist travel tile spawn randomization
  _maps/map_files/vanderlin/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin_forest.dmm
  _maps/map_files/vanderlin/vanderlin_mountain.dmm
  code/__DEFINES/map_switch.dm
  code/__DEFINES/subsystems.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/randomized_travel_tiles.dm
  code/game/alternate_appearance/alternate_appearance.dm
  code/game/alternate_appearance/traveltile.dm
  code/game/objects/structures/traveltile.dm
  vanderlin.dme
Labels: Mapping

#1940 Buff Matron
  code/__DEFINES/traits.dm
  code/datums/stress/negative_events.dm
  code/modules/jobs/job_types/serfs/matron.dm
  code/modules/jobs/job_types/youngfolk/orphan.dm
  code/modules/mob/living/living.dm
  code/modules/spells/spell_types/invoked/matron.dm
  vanderlin.dme
Labels: Feature, Hell Yes

#1992 Removes Legendary Swordsman from Be Special
  code/_globalvars/special_traits/traits.dm
Labels: Removal

#2019 Fix troll axe and chain whip sprites
  icons/roguetown/weapons/32.dmi
Labels: sprites

#2022 Minor Update
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/rosewood/rosewood_forest.dmm
  _maps/map_files/rosewood/rosewood_marsh.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  icons/obj/structures/manabloomtree.dmi
Labels: Mapping

#2017 Removes positive stats from Squire.
  code/modules/jobs/job_types/apprentices/squire.dm
Labels: Removal

#2030 Port proximity monitor updates which includes a shit load of prs
  code/__DEFINES/components.dm
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/signals_atoms/signals_atom_movable.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/subsystems.dm
  code/controllers/subsystem/processing/fields.dm
  code/datums/components/connect/connect_containers.dm
  code/datums/components/connect/connect_loc_behalf.dm
  code/datums/components/connect/connect_range.dm
  code/datums/components/forced_gravity.dm
  code/datums/datum.dm
  code/datums/elements/_element.dm
  code/datums/elements/connect_loc.dm
  code/datums/elements/firestacker.dm
  code/datums/elements/forced_gravity.dm
  code/datums/elements/mob_overlay_effect.dm
  code/datums/elements/tipped_item.dm
  code/datums/emotes.dm
  code/datums/proximity_monitor/_field.dm
  code/datums/proximity_monitor/fields/gravity.dm
  code/datums/proximity_monitor/proximity_monitor.dm
  code/game/atom/atoms.dm
  code/game/atom/atoms_movable.dm
  code/game/objects/effects/proximity.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/bridge.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/maneater.dm
  code/game/objects/structures/rogueflora.dm
  code/game/objects/structures/stairs.dm
  code/game/objects/structures/tangler.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/turf.dm
  code/modules/fields/fields.dm
  code/modules/fields/gravity.dm
  code/modules/fields/turf_objects.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/honeyspider.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/mimic.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/connect_loc.dm
  vanderlin.dme
Labels: Test Merge, Code Maintenance

#1989 Daftmarsh kitchen update.
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
Labels: Mapping, DO NOT MERGE

#2056 Gayyyyyytors and travel tiles - Daftmarsh.
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
  _maps/map_files/shared/CentCom.dmm
Labels: Mapping

#2045 Fix job positions not getting cleared correctly
  code/game/objects/structures/train.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/client/verbs/ghost.dm
Labels: Fix

#2039 Bugfixes and tweaks: Family, wizard robes, large cogwheels, dendor sacrifices
  code/datums/ai/subtrees/dragon_attack.dm
  code/datums/heritage.dm
  code/modules/crafting/quality_of_crafting/_base.dm
  code/modules/crafting/quality_of_crafting/cooking/biscuits.dm
  code/modules/crafting/quality_of_crafting/cooking/misc.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/crafting/slapcrafting/orderless/_base.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/briar.dm
Labels: Fix, Test Merge

#2027 Expand the Vanderlin basin Fort and the surrounding area
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/area/areas/dungeon.dm
  code/game/area/areas/tomb.dm
  code/game/machinery/_machinery.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/doors.dm
  code/game/objects/structures/fake_machines/camera.dm
  code/game/objects/structures/fake_machines/drugmachine.dm
  code/game/objects/structures/fake_machines/merchant.dm
  code/game/objects/structures/fake_machines/money.dm
  code/game/objects/structures/fake_machines/scomm.dm
  code/game/objects/structures/fake_machines/titan.dm
  code/game/objects/structures/fake_machines/vendor.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/maneater.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/redstone.dm
  code/game/objects/structures/tangler.dm
  code/game/objects/structures/window.dm
  code/modules/clothing/clothing.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/mapping/mapping_helpers/structure_helper.dm
  code/modules/mob/living/carbon/human/npc/rousman.dm
  vanderlin.dme
Labels: Mapping

#2047 Remove unused slots and fix default slot priority a bit
  code/__DEFINES/inventory.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/type2type.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/datums/components/anti_magic.dm
  code/datums/components/crafting/crafting.dm
  code/datums/components/explodable.dm
  code/datums/components/spill.dm
  code/datums/keybinding/human.dm
  code/datums/outfit.dm
  code/game/objects/items.dm
  code/game/objects/items/bags.dm
  code/game/objects/items/boxes.dm
  code/game/objects/items/cigs_lighters.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bag.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/weaponry.dm
  code/game/objects/items/weapons/melee/blunt.dm
  code/game/objects/items/weapons/melee/whips.dm
  code/modules/admin/verbs/debug.dm
  code/modules/clothing/face/spectacle.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/jobs/job_types/church/templar.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
  code/modules/mob/living/carbon/human/npc/rousman.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/species_types/other/werewolf.dm
  code/modules/mob/living/carbon/human/topic.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/spirit/inventory.dm
  code/modules/mob/living/carbon/spirit/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/mob.dm
  code/modules/mob/update_icons.dm
  code/modules/projectiles/ammunition/_ammunition.dm
  code/modules/projectiles/boxes_magazines/_ammo_box.dm
  code/modules/projectiles/gun.dm
  code/modules/reagents/reagent_containers/bottles/_bottle.dm
  code/modules/reagents/reagent_containers/glass.dm
  vanderlin.dme
Labels: Fix, Code Maintenance, Removal

#1860 More map lints
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/rosewood/rosewood_forest.dmm
  _maps/map_files/rosewood/rosewood_marsh.dmm
  _maps/map_files/rosewood/rosewood_mountain.dmm
  _maps/map_files/shared/CentCom.dmm
  _maps/map_files/shared/dungeon.dmm
  _maps/map_files/shared/underworld.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin_forest.dmm
  _maps/map_files/vanderlin/vanderlin_mountain.dmm
  _maps/matthios_tomb/hallway/right left floor transition.dmm
  _maps/matthios_tomb/room/GoblinInfestedJoint.dmm
  _maps/matthios_tomb/room/hctomb1.dmm
  _maps/matthios_tomb/room/hctomb3.dmm
  _maps/matthios_tomb/room/hctomb4.dmm
  _maps/matthios_tomb/room/lavafort.dmm
  _maps/matthios_tomb/room/queensretreat.dmm
  _maps/matthios_tomb/room/rousecamp.dmm
  _maps/matthios_tomb/room/small lab.dmm
  _maps/templates/buildings/mines.dmm
  _maps/templates/lil_bog_shack/bog_shack_small_2.dmm
  _maps/templates/lil_bog_shack/bog_shack_small_3.dmm
  _maps/templates/malums_anvil_dungeons/mountaintown.dmm
  _maps/templates/sk_dungeon/small_bog_dungeon_1.dmm
  _maps/templates/sk_dungeon/small_bog_dungeon_3.dmm
  code/game/turfs/open/floor/roguefloor.dm
  tools/UpdatePaths/Scripts/1860_more_lint.txt
  tools/maplint/lints/banned_varedits.yml
  tools/maplint/lints/stair_stacking.yml
Labels: Mapping, Tooling

#2050 One must not rule forever
  code/datums/antag_retainer.dm
  code/datums/skill_holder.dm
  code/modules/antagonists/_common/antag_datum.dm
  code/modules/antagonists/roleobjs/skeleton.dm
  code/modules/antagonists/villain/aspirant.dm
  code/modules/antagonists/villain/bandit.dm
  code/modules/antagonists/villain/peasantrebel.dm
  code/modules/antagonists/villain/werewolf/werewolf.dm
  code/modules/antagonists/villain/zomble.dm
  code/modules/events/antagonist/solo/minor/aspirant.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Feature, Test Merge
