Repository Monkestation/Vanderlin, pull requests merged in 2025-06, with the labels that each got.

#2117 Rosewood Jousting and Inn Update
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/rosewood/rosewood_forest.dmm
  _maps/map_files/rosewood/rosewood_marsh.dmm
Labels: Mapping

#2100 Gives servants cutlery
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#2174 clears up the confession line (accidentaly deleted remote branch its the same pr still though
  code/modules/jobs/job_types/church/inquisitor.dm
Labels: Removal

#2197 (SOUND) Removes all deprecated/unused music
  sound/music/cmode/unused/CombatJailor.ogg
  sound/music/cmode/unused/combat2.ogg
  sound/music/cmode/unused/combat_assassin.ogg
  sound/music/cmode/unused/combat_assassin2.ogg
  sound/music/cmode/unused/combat_bandit.ogg
  sound/music/cmode/unused/combat_bandit_mage.ogg
  sound/music/cmode/unused/combat_barbarian.ogg
  sound/music/cmode/unused/combat_dendor.ogg
  sound/music/cmode/unused/combat_desertrider.ogg
  sound/music/cmode/unused/combat_old.ogg
  sound/music/cmode/unused/combat_vamp.ogg
  sound/music/cmode/unused/combat_vamp2.ogg
  sound/music/unused/siege.ogg
  sound/music/unused/tav1.ogg
  sound/music/unused/tav2.ogg
  sound/music/unused/wartitle.ogg
Labels: Sound, Music, Removal

#2196 Assassin - Remove Whitecloak Disguise
  code/modules/jobs/job_types/adventurer/types/combat/rare/assassin.dm
Labels: Removal

#2194 Atomised glove fix
  icons/roguetown/clothing/onmob/gloves.dmi
Labels: sprites

#2233 Run "rerun_flaky_tests" on CI
  .github/workflows/return_flaky_tests.yml
Labels: Github

#2134 Adds Save Log button to chat
  code/modules/goonchat/browserassets/html/browserOutput.html
  code/modules/goonchat/browserassets/js/browserOutput.js
Labels: Logging

#2243 Rosewood Tweaks again
  _maps/map_files/rosewood/rosewood.dmm
Labels: Mapping

#2159 Object spawners
  _maps/map_files/daftmarsh/daftmarsh.dmm
  _maps/map_files/daftmarsh/daftmarsh_outland.dmm
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin_forest.dmm
  _maps/map_files/vanderlin/vanderlin_mountain.dmm
  code/controllers/subsystem/atoms.dm
  code/controllers/subsystem/randomized_travel_tiles.dm
  code/datums/components/spawner.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/spawners/guaranteed_map_spawner/guaranteed_map_spawner.dm
  code/game/objects/effects/spawners/guaranteed_map_spawner/spawners.dm
  code/game/objects/effects/spawners/map_spawner.dm
  code/game/objects/effects/spawners/spawner.dm
  code/game/objects/effects/spawners/traveltile_spawner.dm
  code/game/objects/structures/traveltile.dm
  icons/obj/structures_spawners.dmi
  vanderlin.dme
Labels: Mapping

#2210 White Palace Pass Map
  _maps/map_files/whitepalacepass.dm
  _maps/map_files/whitepalacepass/WhitePalacePass.dmm
  _maps/map_files/whitepalacepass/map_adjustment_whitepalacepass.dm
  _maps/whitepalacepass.json
  code/datums/map_adjustment_include.dm
  code/game/objects/structures/traps.dm
  code/modules/procedural_mapping/whitepalacepass/field.dm
  config/maps.txt
  vanderlin.dme
Labels: Mapping

#2274 Multiline ahelp
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#2302 Alchemy Herb icon changes + some icon port
  icons/roguetown/misc/alchemy.dmi
  icons/roguetown/misc/herbfoliage.dmi
Labels: sprites
