Repository Monkestation/Vanderlin, pull requests merged in 2025-04, with the labels that each got.

#1307 fixes a coding error in logging
  code/game/atoms.dm
Labels: logging

#597 Adds the Mercenary Guild Master, "Gaffer" Job
  _maps/map_files/vanderlin/otherz/vanderlin_bog.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_forest.dmm
  _maps/map_files/vanderlin/otherz/vanderlin_mountain.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/familytree.dm
  code/controllers/subsystem/roguemachine.dm
  code/datums/components/storage/storage_types.dm
  code/datums/stress/negative_events.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/books.dm
  code/game/objects/items/keyrings.dm
  code/game/objects/items/keys.dm
  code/game/objects/items/natural/animals.dm
  code/game/objects/items/painting.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/game/objects/structures/dock_bell.dm
  code/game/objects/structures/fake_machines/hailers.dm
  code/game/objects/structures/fake_machines/headeater.dm
  code/game/objects/structures/fake_machines/mail.dm
  code/game/objects/structures/fluff.dm
  code/game/objects/structures/train.dm
  code/modules/clothing/belt/misc.dm
  code/modules/clothing/face/eyepatch.dm
  code/modules/clothing/ring/misc.dm
  code/modules/crafting/anvil_recipes/tools.dm
  code/modules/crafting/artificer/misc.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/jobs/job_types/apprentices/servant.dm
  code/modules/jobs/job_types/other/goblin.dm
  code/modules/jobs/job_types/serfs/gaffer.dm
  code/modules/jobs/jobs.dm
  code/modules/mapping/mapping_helpers/access_helper.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
  code/modules/mob/living/carbon/human/npc/rousman.dm
  code/modules/mob/living/carbon/human/npc/skeleton.dm
  code/modules/mob/living/carbon/human/npc/zizombies.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/bigrat.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/bogbug.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/honeyspider.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/mole.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/troll.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/trollbog.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/rogue.dm
  icons/roguetown/clothing/belts.dmi
  icons/roguetown/items/natural.dmi
  icons/roguetown/misc/machines.dmi
  icons/roguetown/misc/tallstructure.dmi
  sound/music/cmode/towner/CombatGaffer.ogg
  sound/music/credits.txt
  stonekeep.dme
  strings/books/Gaff.json
Labels: feature, test merge, Mapping

#1281 Sprite changes to summonable's drops
  icons/roguetown/items/natural.dmi
Labels: sprites

#1324 praise zizo logging
  code/modules/antagonists/villain/zizocult.dm
Labels: Logging

#1335 better lever logging
  code/game/objects/structures/redstone.dm
Labels: Logging

#1325 Improved logging for message spell
  code/modules/spells/spell_types/wizard/utility/message.dm
Labels: Logging

#1302 Hand fix and warning check
  code/game/objects/items/keyrings.dm
Labels: Test Merge, Code Maintenance, Tweak

#1344 Fixes two-handed weapon damage not being improved by quality.
  code/modules/crafting/anvil_recipes/_anvil_recipe.dm
Labels: Fix, Balance

#1250 Trait knockedout
  code/__DEFINES/flags.dm
  code/__DEFINES/mob_timers.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/traits.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/traits.dm
  code/datums/components/soulstoned.dm
  code/datums/skills/craft.dm
  code/datums/status_effects/debuffs.dm
  code/game/atoms_movable.dm
  code/modules/admin/admin_verbs.dm
  code/modules/antagonists/villain/zomble.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/brain/death.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/npc/_npc.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/combat.dm
  code/modules/mob/living/carbon/monkey/monkey_defense.dm
  code/modules/mob/living/carbon/spirit/combat.dm
  code/modules/mob/living/carbon/spirit/spirit_defense.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/animal_defense.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/projectile/magic.dm
  code/modules/surgery/bodyparts/bodypart_dismemberment.dm
  stonekeep.dme
Labels: Fix, Test Merge, Code Maintenance

#1306 Using a travel tile is now logged
  code/game/objects/structures/traveltile.dm
Labels: Test Merge, Logging

#1334 typing indicator logging
  code/game/atoms.dm
Labels: Logging

#1290 Vanderlin Revamp Try 5.5
  _maps/map_files/vanderlin/otherz/vanderlin_bog.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/area/roguetownareas.dm
  code/game/objects/items/keyrings.dm
  code/modules/jobs/job_types/peasants/miner.dm
  code/modules/jobs/job_types/serfs/artificer.dm
  code/modules/jobs/job_types/serfs/physicker.dm
Labels: Test Merge, Mapping

#1188 Reenables roundstart maniac
  _maps/map_files/generic/CentCom.dmm
  code/__DEFINES/role_bans.dm
  code/__DEFINES/role_preferences.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/roundend.dm
  code/controllers/subsystem/storyteller.dm
  code/datums/gods/_patron.dm
  code/datums/gods/patrons/inhumen_pantheon.dm
  code/modules/antagonists/villain/maniac/_maniac.dm
  code/modules/antagonists/villain/maniac/maniac_life.dm
  code/modules/client/preferences.dm
  code/modules/events/antagonist/solo/minor/maniac.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/stats.dm
Labels: Mapping

#1354 Fixes steamknight boiler overlay.
  icons/roguetown/clothing/onmob/steamknight_onmob.dmi
Labels: sprites

#1353 Locks Court Magician to Noc or Zizo.
  code/modules/jobs/job_types/nobility/magician.dm
Labels: Fix, Balance

#955 Lord regent DLC
  code/controllers/subsystem/communications.dm
  code/controllers/subsystem/ticker.dm
  code/game/objects/items/keys.dm
  code/game/objects/structures/fake_machines/titan.dm
  code/modules/jobs/job_types/nobility/hand.dm
Labels: Feature, Test Merge

#1375 some admin improvements.
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Test Merge

#1380 Improved prayer logging for admins.
  code/modules/mob/living/emote.dm
Labels: Logging

#1373 Fixes tights always being white
  code/modules/clothing/pants/tights.dm
Labels: Fix

#1408 Makes accents saved per-character and not per-player
  code/modules/client/preferences_savefile.dm
Labels: Fix, removal

#1341 Bars gate will now crush people.
  code/game/objects/structures/gate.dm
Labels: Test Merge

#1409 logging for beartraps
  code/game/objects/items/beartraps.dm
Labels: Logging

#1323 View latest admin ticket
  code/controllers/subsystem/plexora.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/adminpm.dm
Labels: Administration

#1363 Mannequin Update For Wrists, Neck, Ring Display
  code/game/objects/structures/mannequin.dm
Labels: Test Merge

#1075 New Statistics UI, more statistics
  code/__HELPERS/roundend.dm
  code/_onclick/other_mobs.dm
  code/controllers/subsystem/elastic.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/triumph/triumph_adjust_procs.dm
  code/datums/gods/_patron.dm
  code/game/objects/structures/fake_machines/ATM.dm
  code/game/objects/structures/fake_machines/drugmachine.dm
  code/game/objects/structures/fake_machines/merchant.dm
  code/game/objects/structures/gravemarker.dm
  code/game/objects/structures/newtree.dm
  code/game/objects/structures/rogueflora.dm
  code/modules/client/client_procs.dm
  code/modules/crafting/alchemy/cauldron.dm
  code/modules/crafting/anvil_recipes/_anvil_recipe.dm
  code/modules/farming/soil.dm
  code/modules/farming/wild_plant.dm
  code/modules/fishing/rod.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/emote.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/reagent_containers/powder.dm
  code/modules/spells/spell_types/invoked/acolyte/astrata.dm
  code/modules/spells/spell_types/invoked/acolyte/necra.dm
  code/modules/surgery/organs/organ_internal.dm
Labels: Feature, Test Merge, Code Maintenance, Quality of Life

#1189 The Hand's Room is too dark!!
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#1308 Throwing damage fix
  code/modules/mob/living/living_defense.dm
Labels: Test Merge

#1255 Fix char appearance randomization (#1160)
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix, Test Merge

#1430 Vampire Lord Enhancements
  code/modules/antagonists/villain/vampire/_vampire.dm
  code/modules/antagonists/villain/vampire/lord.dm
  code/modules/spells/spell_types/invoked/vampire.dm
Labels: Feature, Test Merge, Balance

#1437 Some steam armor and harpoon gun fixes
  code/game/objects/items.dm
  code/modules/clothing/armor/steam.dm
Labels: Test Merge

#1433 Gatemaster again because me stupid
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/weapons/melee/whips.dm
  code/modules/clothing/head/helmets/misc.dm
  code/modules/crafting/anvil_recipes/weapons.dm
  code/modules/jobs/job_types/garrison/garrisonguard.dm
  code/modules/jobs/job_types/garrison/gatemaster.dm
  code/modules/jobs/job_types/garrison/men_at_arms.dm
  code/modules/jobs/jobs.dm
  icons/roguetown/weapons/32.dmi
  stonekeep.dme
Labels: Mapping

#1071 The Miasma PR
  code/__DEFINES/pollution.dm
  code/datums/components/rotting.dm
  code/datums/pollutant.dm
  code/datums/pollutants/generic.dm
  code/datums/pollution.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/face/masks.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/npc/goblin.dm
  code/modules/mob/living/carbon/human/npc/orc.dm
  code/modules/mob/living/carbon/human/npc/rousman.dm
  code/modules/mob/living/carbon/human/npc/zizombies.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/familiar.dm
  code/modules/reagents/chemistry/reagents/roguetown.dm
  icons/roguetown/clothing/masks.dmi
Labels: Balance

#1446 (SOUND) Assigns Cleric a Combat Theme
  code/modules/jobs/job_types/adventurer/types/combat/cleric.dm
Labels: Sound, Music

#1445 (SOUND) Replaces Spice Theme
  sound/music/spice.ogg
Labels: Sound, Music

#1449 fixes throat announcement double encode
  code/game/objects/structures/fake_machines/titan.dm
Labels: Fix

#1465 Town dungeon entrance is exit-only
  _maps/map_files/vanderlin/vanderlin.dmm
  code/datums/dungeon_generator/dungeon_entry_exit.dm
  icons/roguetown/misc/portal.dmi
Labels: Mapping

#723 Clothing Equity for Ages and Race Pt.1
  code/modules/clothing/shirts/robe.dm
  code/modules/jobs/job_types/roguetown/nobility/magician.dm
  icons/roguetown/clothing/onmob/belts.dmi
  stonekeep.dme
Labels: Fix

#1167 Post-S&S Rosewood
  _maps/map_files/debug/map_adjustment_template.dm
  _maps/map_files/rosewood.dm
  _maps/map_files/rosewood/map_adjustment_rosewood.dm
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/rosewood/rosewood_forest.dmm
  _maps/map_files/rosewood/rosewood_forest.json
  _maps/map_files/rosewood/rosewood_mountain.dmm
  _maps/map_files/rosewood/rosewood_mountain.json
  _maps/rosewood.json
  code/controllers/subsystem/ticker.dm
  code/datums/map_adjustment_include.dm
  code/datums/map_config.dm
  code/game/area/areas.dm
  code/game/area/roguetownareas.dm
  code/game/objects/lighting/_base_roguestreet.dm
  code/game/objects/lighting/rogue_fires.dm
  code/game/objects/structures/fake_machines/ATM.dm
  code/game/objects/structures/fake_machines/steward.dm
  code/game/objects/structures/rogueflora.dm
  code/game/objects/structures/throne.dm
  code/game/objects/structures/train.dm
  code/game/turfs/closed/wall/fake_window.dm
  code/modules/antagonists/roleobjs/purishep.dm
  code/modules/antagonists/villain/aspirant.dm
  code/modules/antagonists/villain/vampire/lord.dm
  code/modules/clothing/head/crown.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/noble.dm
  code/modules/jobs/job_types/church/priest.dm
  code/modules/jobs/job_types/garrison/forestguard.dm
  code/modules/jobs/job_types/nobility/lord.dm
  code/modules/jobs/job_types/nobility/minor_noble.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/troll.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/red_dragon.dm
  code/modules/paperwork/rogue.dm
  code/modules/procedural_mapping/rosewood/cave.dm
  code/modules/procedural_mapping/rosewood/field.dm
  code/modules/procedural_mapping/rosewood/forest.dm
  code/modules/procedural_mapping/rosewood/howling.dm
  config/maps.txt
  icons/roguetown/misc/64x64.dmi
  icons/roguetown/misc/foliage.dmi
  icons/roguetown/misc/lighting.dmi
  icons/roguetown/misc/tallstructure.dmi
  sound/misc/stings/RosewoodSting.ogg
  stonekeep.dme
  tools/UpdatePaths/Scripts/1167_rosewoodaccess.txt
Labels: Test Merge, Mapping

#1439 Men at arms have bevors
  code/modules/jobs/job_types/garrison/men_at_arms.dm
  icons/roguetown/clothing/onmob/64x64/head.dmi
Labels: Fix, Balance

#1478 fix prayer admin logging
  code/modules/mob/living/emote.dm
Labels: Logging

#1519 Massives reduces restricted roles for antag rolling, blocks storyteller from triggering maniac events after triumphing
  code/modules/events/antagonist/migrant_waves/crazed_maniac.dm
  code/modules/events/antagonist/solo/lich.dm
  code/modules/events/antagonist/solo/minor/bandits.dm
  code/modules/events/antagonist/solo/minor/maniac.dm
  code/modules/events/antagonist/solo/rebels.dm
  code/modules/events/antagonist/solo/vampires.dm
  code/modules/events/antagonist/solo/vampires_and_werewolves.dm
  code/modules/events/antagonist/solo/werewolfs.dm
  code/modules/events/antagonist/solo/zizo_cult.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
Labels: Balance

#1521 Gives Town Elder their Alzheimer's medication
  code/modules/jobs/job_types/garrison/mayor.dm
Labels: Balance, Tweak

#1498 Wooden mallet has craftdiff of 0
  code/modules/crafting/quality_of_crafting/crafting.dm
Labels: Balance

#1538 Fix human runtime
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#1551 Removes veterans scout and spy classes
  code/modules/jobs/job_types/garrison/veteran.dm
Labels: Balance, removal

#1349 Adds a new Troll variant: Cave Trolls! (and also cleans up troll code, oh and also dendor taming chance)
  code/__DEFINES/animals.dm
  code/__DEFINES/roguetown.dm
  code/datums/actions/mob_actions/stone_throw.dm
  code/datums/ai/controllers/bog_troll.dm
  code/datums/ai/controllers/troll.dm
  code/game/area/roguetownareas.dm
  code/game/area/vanderlin/vanderlinareas.dm
  code/game/objects/items/bait.dm
  code/game/objects/items/natural/animals.dm
  code/game/objects/structures/rogueflora.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/troll.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/trollbog.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/procedural_mapping/mapGeneratorModules/cavefloor.dm
  code/modules/spells/spell_types/invoked/acolyte/dendor.dm
  icons/roguetown/items/natural.dmi
  icons/roguetown/mob/monster/trolls/cave_troll.dmi
  icons/roguetown/mob/monster/trolls/default_troll.dmi
  modular/Mapping/Mapping_aides.dm
  vanderlin.dme
Labels: Mapping

#1477 Fixes Miners Quarters having no key opening it
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#1492 Gives kobolds their own mockery text
  strings/bard.json
Labels: Feature, Tweak

#1499 Fixes Apothecary peddler + light up a bit the garden (Rosewood)
  _maps/map_files/rosewood/rosewood.dmm
Labels: Mapping

#1528 Minor fixes
  code/modules/crafting/alchemy/mortarpestle.dm
  code/modules/crafting/slapcrafting/orderless/pies.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: Fix

#1562 Removes Multi-Round Join Restrictions from Two Roles
  code/modules/jobs/job_types/youngfolk/churchling.dm
  code/modules/jobs/job_types/youngfolk/innkeepchild.dm
Labels: removal

#1463 Coin splitting is accurate
  code/game/objects/items/coins.dm
Labels: Test Merge

#1487 Youngling werewolf sprite
  code/modules/mob/living/carbon/human/species_types/other/werewolf.dm
  icons/roguetown/mob/monster/werewolf.dmi
Labels: Test Merge

#1452 allows normal mana potions to be used for amythorz transmutation
  code/modules/crafting/quality_of_crafting/arcyne.dm
Labels: Test Merge

#1542 Soap improvements
  code/controllers/subsystem/atoms.dm
  code/datums/components/cleaner.dm
  code/datums/liquids/liquid_group.dm
  code/game/objects/items/natural/clothfibersthorn.dm
  code/game/objects/items/soap.dm
  code/game/turfs/open/_open.dm
  code/modules/farming/tools.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/farm/trufflepig.dm
  vanderlin.dme
Labels: Test Merge

#1587 changes the bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Github

#1579 Decorated Wall Smoothening, + Erebus + Floor types.
  _maps/map_files/shared/underworld.dmm
  code/game/turfs/closed/wall/walls.dm
  code/game/turfs/open/floor/roguefloor.dm
  icons/turf/floors.dmi
  icons/turf/walls/church_stone.dmi
  icons/turf/walls/church_stone_mossy.dmi
  icons/turf/walls/church_stone_mossyblue.dmi
  icons/turf/walls/church_stone_mossyred.dmi
  icons/turf/walls/underbrick.dmi
  icons/turf/walls/underworld_brick.dmi
Labels: Mapping, sprites

#1454 Inquisition Changes
  code/__DEFINES/span.dm
  code/datums/components/storage/storage_types.dm
  code/datums/enchantments/silver.dm
  code/datums/migrants/waves/crusader_wave.dm
  code/datums/stress/negative_events.dm
  code/game/objects/items.dm
  code/game/objects/items/bedsheets.dm
  code/game/objects/items/weapons/ranged/ammo.dm
  code/game/objects/structures/fake_machines/mail.dm
  code/modules/clothing/armor/medium.dm
  code/modules/clothing/belt/misc.dm
  code/modules/clothing/face/spectacle.dm
  code/modules/clothing/gloves/leather.dm
  code/modules/clothing/head/job_hats.dm
  code/modules/clothing/quivers/misc.dm
  code/modules/clothing/shoes/misc.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/crafting/quality_of_crafting/weaving.dm
  code/modules/goonchat/browserassets/css/browserOutput.css
  code/modules/jobs/job_types/church/inquisitor.dm
  code/modules/jobs/job_types/garrison/royalguard.dm
  code/modules/mob/living/carbon/stress.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/rogue.dm
  code/modules/surgery/bodyparts/bodypart_wounds.dm
  icons/roguetown/clothing/armor.dmi
  icons/roguetown/clothing/feet.dmi
  icons/roguetown/clothing/gloves.dmi
  icons/roguetown/clothing/masks.dmi
  icons/roguetown/clothing/onmob/armor.dmi
  icons/roguetown/clothing/onmob/feet.dmi
  icons/roguetown/clothing/onmob/gloves.dmi
  icons/roguetown/clothing/onmob/head.dmi
  icons/roguetown/clothing/onmob/helpers/sleeves_armor_inqui.dmi
  icons/roguetown/clothing/onmob/masks.dmi
  interface/stylesheet.dm
  vanderlin.dme
Labels: Test Merge, Balance, Unatomized

#1536 Buff and clean up transfix
  code/modules/antagonists/villain/vampire/actions.dm
  code/modules/antagonists/villain/vampire/lord.dm
  code/modules/antagonists/villain/vampire/team.dm
Labels: Test Merge, Balance, Code Maintenance

#1517 Ports some optimization and cleanup
  code/_globalvars/lists/flavor_misc.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/particle_weather.dm
  code/controllers/subsystem/soundloopers.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/particle_weathers/_base.dm
  code/game/objects/inhand_helpers.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/dmusicbox.dm
  code/game/objects/lighting/_base_roguelight.dm
  code/game/objects/structures/musicbox.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/procedural_mapping/mapGeneratorModule.dm
  code/modules/spells/spell_types/wizard/utility/prestidigitation.dm
  modular/Barding/code/Barding_instruments.dm
Labels: Fix, Test Merge, Code Maintenance, Sound

#1279 add tapster/alemaid and orphanage assistant and ring servant
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/effects/landmarks.dm
  code/modules/jobs/job_types/apprentices/servant.dm
Labels: Mapping

#1512 Lava refactor
  code/__DEFINES/particle_weather.dm
  code/game/objects/items/mageitems.dm
  code/game/objects/items/natural/ash.dm
  code/game/objects/items/weapons/melee/special.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/open/lava.dm
  code/modules/mob/living/living_defines.dm
Labels: Test Merge, Code Maintenance

#1317 Stockpile, Treasury, and Literature Changes
  _maps/map_files/shared/CentCom.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/time.dm
  code/controllers/subsystem/librarian.dm
  code/controllers/subsystem/treasury.dm
  code/datums/stock/bounties.dm
  code/datums/stock/import.dm
  code/datums/stock/stockpile.dm
  code/game/objects/items/books.dm
  code/game/objects/items/coins.dm
  code/game/objects/items/literary.dm
  code/game/objects/items/natural/animals.dm
  code/game/objects/items/painting/canvas.dm
  code/game/objects/items/weapons/ranged/ammo.dm
  code/game/objects/items/weapons/ranged/crossbows.dm
  code/game/objects/structures/fake_machines/ATM.dm
  code/game/objects/structures/fake_machines/steward.dm
  code/game/objects/structures/fake_machines/stockpile.dm
  code/game/objects/structures/fake_machines/submission.dm
  code/game/objects/structures/fluff.dm
  code/modules/cargo/supply_packs/armor.dm
  code/modules/cargo/supply_packs/drinks.dm
  code/modules/cargo/supply_packs/food.dm
  code/modules/cargo/supply_packs/jewelry.dm
  code/modules/cargo/supply_packs/livestock.dm
  code/modules/cargo/supply_packs/luxury.dm
  code/modules/cargo/supply_packs/rawmat.dm
  code/modules/cargo/supply_packs/seeds.dm
  code/modules/cargo/supply_packs/tools.dm
  code/modules/cargo/supply_packs/weapons.dm
  code/modules/crafting/quality_of_crafting/_base.dm
  code/modules/crafting/quality_of_crafting/crafting.dm
  code/modules/crafting/quality_of_crafting/generic.dm
  code/modules/crafting/quality_of_crafting/reading.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/farming/produce.dm
  code/modules/farming/seeds.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/apprentices/prince.dm
  code/modules/jobs/job_types/garrison/forestguard.dm
  code/modules/jobs/job_types/garrison/forestwarden.dm
  code/modules/jobs/job_types/garrison/veteran.dm
  code/modules/jobs/job_types/nobility/archivist.dm
  code/modules/jobs/job_types/nobility/captain.dm
  code/modules/jobs/job_types/nobility/consort.dm
  code/modules/jobs/job_types/nobility/hand.dm
  code/modules/jobs/job_types/nobility/merchant.dm
  code/modules/jobs/job_types/nobility/minor_noble.dm
  code/modules/jobs/job_types/nobility/steward.dm
  code/modules/jobs/job_types/serfs/matron.dm
  code/modules/library/lib_machines.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/rogue.dm
  icons/roguetown/items/books.dmi
  vanderlin.dme
Labels: Mapping

#1483 Boat QOL and Refactor, Merchant faction buffs
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  code/__DEFINES/dcs/signals_atoms/signals_atom_movement.dm
  code/__DEFINES/jobs.dm
  code/__HELPERS/player_helpers.dm
  code/controllers/subsystem/merchant.dm
  code/controllers/subsystem/painting.dm
  code/datums/components/strong_pull.dm
  code/datums/gods/patrons/patrons_blessings.dm
  code/datums/migrants/migrant_job.dm
  code/game/atoms_movable.dm
  code/game/machinery/trams_and_elevators/lift_master.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/books.dm
  code/game/objects/items/coins.dm
  code/game/objects/items/keyrings.dm
  code/game/objects/structures/crates_lockers/chest.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/dock_bell.dm
  code/game/objects/structures/fake_machines/steward.dm
  code/game/objects/structures/fake_machines/titan.dm
  code/modules/cargo/exports.dm
  code/modules/cargo/supply_packs/_pack.dm
  code/modules/cargo/supply_packs/rawmat.dm
  code/modules/clothing/shirts/undershirt.dm
  code/modules/jobs/job_types/_job.dm
  code/modules/jobs/job_types/adventurer/adventurer.dm
  code/modules/jobs/job_types/adventurer/bandit.dm
  code/modules/jobs/job_types/adventurer/pilgrim.dm
  code/modules/jobs/job_types/apprentices/shophand.dm
  code/modules/jobs/job_types/nobility/archivist.dm
  code/modules/jobs/job_types/nobility/merchant.dm
  code/modules/jobs/job_types/other/mercenary.dm
  code/modules/jobs/job_types/peasants/butler.dm
  code/modules/jobs/job_types/peasants/grabber.dm
  code/modules/jobs/jobs.dm
  code/modules/mob/dead/new_player/new_player.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/paperwork/rogue.dm
  vanderlin.dme
Labels: Code Maintenance, Mapping

#1607 Removes ambush alert sound when being ambushed
  code/modules/mob/living/ambush.dm
Labels: Balance, removal

#1205 Town Elder role Revamp
  code/__DEFINES/jobs.dm
  code/__DEFINES/roguetown.dm
  code/__DEFINES/traits.dm
  code/controllers/subsystem/storyteller.dm
  code/datums/sleep_advancement.dm
  code/datums/status_effects/rogue/roguebuff.dm
  code/game/area/roguetownareas.dm
  code/game/objects/items/keyrings.dm
  code/modules/jobs/job_types/garrison/mayor.dm
  code/modules/jobs/job_types/garrison/town_elder.dm
  code/modules/jobs/jobs.dm
  vanderlin.dme
Labels: Feature, Test Merge, Balance

#1552 Fix dirty varedit in rosewood
  _maps/map_files/rosewood/rosewood.dmm
Labels: Mapping

#1416 [PORT] Plexora optimizations
  .github/ISSUE_TEMPLATE/config.yml
  README.md
  code/__DEFINES/plexora.dm
  code/controllers/configuration/entries/plexora.dm
  code/controllers/subsystem/plexora.dm
  code/game/world.dm
  code/modules/admin/admin.dm
  code/modules/tgs/core/core.dm
  config/config.txt
  config/motd.txt
  config/plexora.json
  config/plexora.txt
  vanderlin.dme
Labels: Github

#1572 Remove barricade rogue pathing and make them drop planks
  _maps/map_files/roguetown/roguetown.dmm
  _maps/map_files/roguetown/smalldecap.dmm
  _maps/map_files/roguetown/smallforest.dmm
  _maps/map_files/roguetown/smallswamp.dmm
  _maps/map_files/rosewood/rosewood_mountain.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
  _maps/map_files/vanderlin/vanderlin_mountain.dmm
  _maps/matthios_tomb/hallway/HolyGrailHall.dmm
  _maps/matthios_tomb/hallway/MowPiece2.dmm
  _maps/matthios_tomb/hallway/Wild Dungeon Medium.dmm
  _maps/matthios_tomb/room/AcidMageTower.dmm
  _maps/matthios_tomb/room/GoblinInfestedJoint.dmm
  _maps/matthios_tomb/room/SmallChurch.dmm
  _maps/matthios_tomb/room/Thelastbreath.dmm
  _maps/matthios_tomb/room/TownRuins.dmm
  _maps/matthios_tomb/room/goblincamp.dmm
  _maps/matthios_tomb/room/hctomb1.dmm
  _maps/matthios_tomb/room/hctomb3.dmm
  _maps/matthios_tomb/room/hctomb4.dmm
  _maps/templates/malums_anvil_dungeons/embercradle.dmm
  _maps/templates/malums_anvil_dungeons/mountaintown.dmm
  code/game/objects/structures/barricades.dm
  icons/obj/structures/barricade.dmi
  icons/roguetown/misc/structure.dmi
  tools/UpdatePaths/Scripts/1572_roguebarricade.txt
Labels: Test Merge, Mapping, removal

#1568 Ports ratwood infernal feather behavior, makes it actually work.
  code/modules/paperwork/paper.dm
Labels: Test Merge

#1502 Gives jobs BITFLAG_CONSTRUCTOR
  code/modules/jobs/job_types/apprentices/bapprentice.dm
  code/modules/jobs/job_types/nobility/nightman.dm
  code/modules/jobs/job_types/peasants/butcher.dm
  code/modules/jobs/job_types/peasants/cheesemaker.dm
  code/modules/jobs/job_types/peasants/cook.dm
  code/modules/jobs/job_types/peasants/fisher.dm
  code/modules/jobs/job_types/peasants/gravedigger.dm
  code/modules/jobs/job_types/peasants/hunter.dm
  code/modules/jobs/job_types/peasants/miner.dm
  code/modules/jobs/job_types/peasants/soilson.dm
  code/modules/jobs/job_types/serfs/artificer.dm
  code/modules/jobs/job_types/serfs/blacksmith.dm
  code/modules/jobs/job_types/serfs/carpenter.dm
  code/modules/jobs/job_types/serfs/innkeep.dm
  code/modules/jobs/job_types/serfs/tailor.dm
  code/modules/jobs/job_types/youngfolk/churchling.dm
  code/modules/jobs/job_types/youngfolk/innkeepchild.dm
Labels: Test Merge, Tweak

#1524 Character Flaw : Tongueless
  code/datums/character_flaw/_character_flaw.dm
  code/datums/wounds/special.dm
Labels: Test Merge

#1618 Removes orphanage assistant and cheesemaker from roundstart
  code/modules/jobs/job_types/adventurer/adventurer.dm
  code/modules/jobs/job_types/adventurer/types/pilgrim/cheesemaker.dm
  code/modules/jobs/job_types/apprentices/servant.dm
  code/modules/jobs/job_types/peasants/cheesemaker.dm
  code/modules/jobs/jobs.dm
Labels: removal

#1615 fixes prayer logging runtime
  code/modules/mob/living/emote.dm
Labels: Logging

#1602 vanderlin merc guild revamp and minor rosewood merc guild adjustments
  _maps/map_files/rosewood/rosewood.dmm
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Test Merge, Mapping

#1549 Adds small abandoned pilgrim village, thatchwood
  _maps/map_files/vanderlin/vanderlin_forest.dmm
Labels: Feature, Test Merge, Mapping

#1638 (SOUND) Changes imsick.ogg
  sound/villain/imsick.ogg
Labels: Sound

#1605 Cursor Changes
  code/game/objects/items/weapons/intents.dm
  icons/effects/mousemice/charge/default/0.dmi
  icons/effects/mousemice/charge/default/10.dmi
  icons/effects/mousemice/charge/default/100.dmi
  icons/effects/mousemice/charge/default/15.dmi
  icons/effects/mousemice/charge/default/20.dmi
  icons/effects/mousemice/charge/default/25.dmi
  icons/effects/mousemice/charge/default/30.dmi
  icons/effects/mousemice/charge/default/35.dmi
  icons/effects/mousemice/charge/default/40.dmi
  icons/effects/mousemice/charge/default/45.dmi
  icons/effects/mousemice/charge/default/5.dmi
  icons/effects/mousemice/charge/default/50.dmi
  icons/effects/mousemice/charge/default/55.dmi
  icons/effects/mousemice/charge/default/60.dmi
  icons/effects/mousemice/charge/default/65.dmi
  icons/effects/mousemice/charge/default/70.dmi
  icons/effects/mousemice/charge/default/75.dmi
  icons/effects/mousemice/charge/default/80.dmi
  icons/effects/mousemice/charge/default/85.dmi
  icons/effects/mousemice/charge/default/90.dmi
  icons/effects/mousemice/charge/default/95.dmi
  icons/effects/mousemice/charge/shield_charged.dmi
  icons/effects/mousemice/charge/shield_charging.dmi
  icons/effects/mousemice/charge/spell_charged.dmi
  icons/effects/mousemice/charge/spell_charging.dmi
  icons/effects/mousemice/human.dmi
  icons/effects/mousemice/human_attack.dmi
  icons/effects/mousemice/human_give.dmi
  icons/effects/mousemice/human_jump.dmi
  icons/effects/mousemice/human_kick.dmi
  icons/effects/mousemice/human_looking.dmi
Labels: Test Merge, sprites

#1606 Suggested Changes
  code/datums/pollutants/generic.dm
  code/datums/status_effects/debuffs.dm
  code/datums/stock/stockpile.dm
  code/game/objects/herbs.dm
  code/game/objects/items/tools/hammer.dm
  code/game/objects/items/weapons/melee/swords.dm
  code/game/objects/structures/beds_chairs/roguechair.dm
  code/game/objects/structures/fake_machines/stockpile.dm
  code/game/objects/structures/hole.dm
  code/game/objects/structures/rogueflora.dm
  code/modules/clothing/belt/misc.dm
  code/modules/crafting/quality_of_crafting/leatherworking.dm
  code/modules/crafting/quality_of_crafting/sewing.dm
  code/modules/farming/wild_plant.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Test Merge

#1621 Port unit test updates
  code/__DEFINES/unit_tests.dm
  code/__HELPERS/_lists.dm
  code/datums/map_config.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/anchored_mobs.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/focus_only_tests.dm
  code/modules/unit_tests/reagent_id_typos.dm
  code/modules/unit_tests/reagent_names.dm
  code/modules/unit_tests/reagent_recipe_collisions.dm
  code/modules/unit_tests/rogue_inhands.dm
  code/modules/unit_tests/roguetown_clothing.dm
  code/modules/unit_tests/species_whitelists.dm
  code/modules/unit_tests/subsystem_init.dm
  code/modules/unit_tests/surgeries.dm
  code/modules/unit_tests/timer_sanity.dm
  code/modules/unit_tests/unit_test.dm
  vanderlin.dme
Labels: Unit Tests

#1624 readd rosewood trolls
  _maps/map_files/rosewood/rosewood.dmm
  code/modules/mob/living/simple_animal/hostile/retaliate/creacher/troll.dm
Labels: Mapping

#1642 lich command undead logging
  code/modules/spells/spell_types/invoked/necromancer.dm
Labels: Logging

#1645 Fix rosewood wall varedits
  _maps/map_files/rosewood/rosewood.dmm
  code/game/turfs/closed/wall/walls.dm
  tools/UpdatePaths/Scripts/1645_groovewall.txt
Labels: Mapping

#1682 removes some world loops
  code/controllers/subsystem/ticker.dm
  code/modules/admin/verbs/manipulate_organs.dm
Labels: removal

#1678 vanderlin hotsprings
  _maps/map_files/vanderlin/vanderlin.dmm
Labels: Mapping

#1685 improved logs for spell casting
  code/modules/spells/spell.dm
Labels: Logging

#1691 [Bug Fix] Spangenhelm worn sprite fix
  icons/roguetown/clothing/special/onmob/spangenhelm_worn.dmi
Labels: sprites

#1690 Beartrap logs fixes
  code/game/objects/items/beartraps.dm
Labels: Logging

#1346 Adv mage nerf + mage apprentice buff
  _maps/map_files/vanderlin/vanderlin.dmm
  code/game/objects/items/mageitems.dm
  code/modules/jobs/job_types/adventurer/types/combat/mage.dm
  code/modules/jobs/job_types/adventurer/types/combat/sorceress.dm
  code/modules/jobs/job_types/apprentices/wapprentice.dm
Labels: Balance, Mapping
